import type { GovernmentPartner } from "@/lib/practiceAreas";

export const saudiMinistries: GovernmentPartner[] = [
  {
    key: "interior",
    en: "Ministry of Interior",
    ar: "وزارة الداخلية",
    logo: "/images/government/saudi/interior.png",
    url: "https://www.moi.gov.sa",
  },
  {
    key: "national-guard",
    en: "Ministry of National Guard",
    ar: "وزارة الحرس الوطني",
    logo: "/images/government/saudi/national-guard.png",
    url: "https://www.sang.gov.sa",
  },
  {
    key: "defense",
    en: "Ministry of Defense",
    ar: "وزارة الدفاع",
    logo: "/images/government/saudi/defense.png",
    url: "https://www.mod.gov.sa",
  },
  {
    key: "foreign-affairs",
    en: "Ministry of Foreign Affairs",
    ar: "وزارة الخارجية",
    logo: "/images/government/saudi/foreign-affairs.png",
    url: "https://www.mofa.gov.sa",
  },
  {
    key: "islamic-affairs",
    en: "Ministry of Islamic Affairs, Dawah and Guidance",
    ar: "وزارة الشؤون الإسلامية والدعوة والإرشاد",
    logo: "/images/government/saudi/islamic-affairs.png",
    url: "https://www.moia.gov.sa",
  },
  {
    key: "education",
    en: "Ministry of Education",
    ar: "وزارة التعليم",
    logo: "/images/government/saudi/education.png",
    url: "https://www.moe.gov.sa",
  },
  {
    key: "health",
    en: "Ministry of Health",
    ar: "وزارة الصحة",
    logo: "/images/government/saudi/health.png",
    url: "https://www.moh.gov.sa",
  },
  {
    key: "commerce",
    en: "Ministry of Commerce",
    ar: "وزارة التجارة",
    logo: "/images/government/saudi/commerce.png",
    url: "https://mc.gov.sa",
  },
  {
    key: "energy",
    en: "Ministry of Energy",
    ar: "وزارة الطاقة",
    logo: "/images/government/saudi/energy.png",
    url: "https://www.moenergy.gov.sa",
  },
  {
    key: "industry-mineral-resources",
    en: "Ministry of Industry and Mineral Resources",
    ar: "وزارة الصناعة والثروة المعدنية",
    logo: "/images/government/saudi/industry-mineral-resources.png",
    url: "https://mim.gov.sa",
  },
  {
    key: "environment-water-agriculture",
    en: "Ministry of Environment, Water and Agriculture",
    ar: "وزارة البيئة والمياه والزراعة",
    logo: "/images/government/saudi/environment-water-agriculture.png",
    url: "https://www.mewa.gov.sa",
  },
  {
    key: "hajj-umrah",
    en: "Ministry of Hajj and Umrah",
    ar: "وزارة الحج والعمرة",
    logo: "/images/government/saudi/hajj-umrah.png",
    url: "https://www.haj.gov.sa",
  },
  {
    key: "justice",
    en: "Ministry of Justice",
    ar: "وزارة العدل",
    logo: "/images/government/saudi/justice.png",
    url: "https://www.moj.gov.sa",
  },
  {
    key: "human-resources",
    en: "Ministry of Human Resources and Social Development",
    ar: "وزارة الموارد البشرية والتنمية الاجتماعية",
    logo: "/images/government/saudi/human-resources.png",
    url: "https://www.hrsd.gov.sa",
  },
  {
    key: "media",
    en: "Ministry of Media",
    ar: "وزارة الإعلام",
    logo: "/images/government/saudi/media.png",
    url: "https://media.gov.sa",
  },
  {
    key: "finance",
    en: "Ministry of Finance",
    ar: "وزارة المالية",
    logo: "/images/government/saudi/finance.png",
    url: "https://www.mof.gov.sa",
  },
  {
    key: "economy-planning",
    en: "Ministry of Economy and Planning",
    ar: "وزارة الاقتصاد والتخطيط",
    logo: "/images/government/saudi/economy-planning.png",
    url: "https://www.mep.gov.sa",
  },
  {
    key: "municipalities-housing",
    en: "Ministry of Municipalities and Housing",
    ar: "وزارة البلديات والإسكان",
    logo: "/images/government/saudi/municipalities-housing.png",
    url: "https://momah.gov.sa",
  },
  {
    key: "communications-it",
    en: "Ministry of Communications and Information Technology",
    ar: "وزارة الاتصالات وتقنية المعلومات",
    logo: "/images/government/saudi/communications-it.png",
    url: "https://www.mcit.gov.sa",
  },
  {
    key: "transport-logistics",
    en: "Ministry of Transport and Logistics Services",
    ar: "وزارة النقل والخدمات اللوجستية",
    logo: "/images/government/saudi/transport-logistics.png",
    url: "https://mot.gov.sa",
  },
  {
    key: "tourism",
    en: "Ministry of Tourism",
    ar: "وزارة السياحة",
    logo: "/images/government/saudi/tourism.png",
    url: "https://mt.gov.sa",
  },
  {
    key: "investment",
    en: "Ministry of Investment",
    ar: "وزارة الاستثمار",
    logo: "/images/government/saudi/investment.png",
    url: "https://misa.gov.sa",
  },
  {
    key: "sport",
    en: "Ministry of Sport",
    ar: "وزارة الرياضة",
    logo: "/images/government/saudi/sport.png",
    url: "https://www.mos.gov.sa",
  },
  {
    key: "culture",
    en: "Ministry of Culture",
    ar: "وزارة الثقافة",
    logo: "/images/government/saudi/culture.png",
    url: "https://www.moc.gov.sa",
  },
];
