import { and, desc, eq, getTableColumns, ilike, ne, or, sql, type SQLWrapper } from "drizzle-orm";
import { db } from "@/lib/db/client";
import { sarayaOwners, sarayaProperties, sarayaPropertyMemberships, sarayaTenantOrganizations, sarayaUnits, sarayaUnitTypes, sarayaUsers } from "@/lib/db/saraya-schema";
import type { ManagementRepository, RepositoryQuery, Resource } from "./service";

const pageCondition = (table: { createdAt: SQLWrapper; id: SQLWrapper }, query: RepositoryQuery) => query.cursor ? sql`(${table.createdAt} < ${new Date(query.cursor.createdAt)} OR (${table.createdAt} = ${new Date(query.cursor.createdAt)} AND ${table.id} < ${query.cursor.id}))` : undefined;
const staffFields = {
  id: sarayaPropertyMemberships.id,
  userId: sarayaPropertyMemberships.userId,
  displayNameAr: sarayaUsers.displayNameAr,
  displayNameEn: sarayaUsers.displayNameEn,
  email: sarayaUsers.normalizedEmail,
  phone: sarayaUsers.normalizedPhone,
  role: sarayaPropertyMemberships.role,
  isActive: sarayaPropertyMemberships.isActive,
  createdAt: sarayaPropertyMemberships.createdAt,
  updatedAt: sarayaPropertyMemberships.updatedAt,
};

async function list(resource: Resource, propertyId: string, query: RepositoryQuery): Promise<unknown[]> {
  const count = query.limit + 1;
  switch (resource) {
    case "properties": return db.select().from(sarayaProperties).where(and(eq(sarayaProperties.id, propertyId), query.search ? or(ilike(sarayaProperties.nameAr, `%${query.search}%`), ilike(sarayaProperties.nameEn, `%${query.search}%`), ilike(sarayaProperties.code, `%${query.search}%`)) : undefined, pageCondition(sarayaProperties, query))).orderBy(desc(sarayaProperties.createdAt), desc(sarayaProperties.id)).limit(count);
    case "units": return db.select({ ...getTableColumns(sarayaUnits), resolvedRentalApprovalMode: sql<"instant" | "owner_review">`COALESCE(${sarayaUnits.rentalApprovalOverride}, ${sarayaProperties.rentalApprovalMode})` }).from(sarayaUnits).innerJoin(sarayaProperties, eq(sarayaProperties.id, sarayaUnits.propertyId)).where(and(eq(sarayaUnits.propertyId, propertyId), query.ownerId ? eq(sarayaUnits.ownerId, query.ownerId) : undefined, query.status ? eq(sarayaUnits.status, query.status as typeof sarayaUnits.$inferSelect.status) : undefined, query.search ? ilike(sarayaUnits.unitNumber, `%${query.search}%`) : undefined, pageCondition(sarayaUnits, query))).orderBy(desc(sarayaUnits.createdAt), desc(sarayaUnits.id)).limit(count);
    case "tenants": return db.select().from(sarayaTenantOrganizations).where(and(eq(sarayaTenantOrganizations.propertyId, propertyId), query.status === "active" ? eq(sarayaTenantOrganizations.isActive, true) : query.status === "inactive" ? eq(sarayaTenantOrganizations.isActive, false) : undefined, query.search ? or(ilike(sarayaTenantOrganizations.nameAr, `%${query.search}%`), ilike(sarayaTenantOrganizations.nameEn, `%${query.search}%`), ilike(sarayaTenantOrganizations.registrationNumber, `%${query.search}%`)) : undefined, pageCondition(sarayaTenantOrganizations, query))).orderBy(desc(sarayaTenantOrganizations.createdAt), desc(sarayaTenantOrganizations.id)).limit(count);
    case "owners": return db.select().from(sarayaOwners).where(and(eq(sarayaOwners.propertyId, propertyId), query.search ? or(ilike(sarayaOwners.nameAr, `%${query.search}%`), ilike(sarayaOwners.nameEn, `%${query.search}%`), ilike(sarayaOwners.registrationNumber, `%${query.search}%`)) : undefined, pageCondition(sarayaOwners, query))).orderBy(desc(sarayaOwners.createdAt), desc(sarayaOwners.id)).limit(count);
    case "staff": return db.select(staffFields).from(sarayaPropertyMemberships).innerJoin(sarayaUsers, eq(sarayaUsers.id, sarayaPropertyMemberships.userId)).where(and(eq(sarayaPropertyMemberships.propertyId, propertyId), query.role ? eq(sarayaPropertyMemberships.role, query.role as typeof sarayaPropertyMemberships.$inferSelect.role) : undefined, query.search ? or(ilike(sarayaUsers.displayNameAr, `%${query.search}%`), ilike(sarayaUsers.displayNameEn, `%${query.search}%`), ilike(sarayaUsers.normalizedEmail, `%${query.search}%`), ilike(sarayaUsers.normalizedPhone, `%${query.search}%`)) : undefined, pageCondition(sarayaPropertyMemberships, query))).orderBy(desc(sarayaPropertyMemberships.createdAt), desc(sarayaPropertyMemberships.id)).limit(count);
  }
}
async function get(resource: Resource, propertyId: string, id: string): Promise<unknown | null> { const rows = resource === "properties" ? await db.select().from(sarayaProperties).where(and(eq(sarayaProperties.id, id), eq(sarayaProperties.id, propertyId))).limit(1) : resource === "units" ? await db.select().from(sarayaUnits).where(and(eq(sarayaUnits.propertyId, propertyId), eq(sarayaUnits.id, id))).limit(1) : resource === "tenants" ? await db.select().from(sarayaTenantOrganizations).where(and(eq(sarayaTenantOrganizations.propertyId, propertyId), eq(sarayaTenantOrganizations.id, id))).limit(1) : resource === "owners" ? await db.select().from(sarayaOwners).where(and(eq(sarayaOwners.propertyId, propertyId), eq(sarayaOwners.id, id))).limit(1) : await db.select(staffFields).from(sarayaPropertyMemberships).innerJoin(sarayaUsers, eq(sarayaUsers.id, sarayaPropertyMemberships.userId)).where(and(eq(sarayaPropertyMemberships.propertyId, propertyId), eq(sarayaPropertyMemberships.id, id))).limit(1); return rows[0] ?? null; }
async function create(resource: Exclude<Resource, "properties">, value: Record<string, unknown>) { if (resource === "units") return (await db.insert(sarayaUnits).values(value as typeof sarayaUnits.$inferInsert).returning())[0]; if (resource === "tenants") return (await db.insert(sarayaTenantOrganizations).values(value as typeof sarayaTenantOrganizations.$inferInsert).returning())[0]; if (resource === "owners") return (await db.insert(sarayaOwners).values(value as typeof sarayaOwners.$inferInsert).returning())[0]; return (await db.insert(sarayaPropertyMemberships).values(value as typeof sarayaPropertyMemberships.$inferInsert).returning())[0]; }
async function createPropertyForAdmin(value: Record<string, unknown>, actorUserId: string) { return db.transaction(async (tx) => { const [property] = await tx.insert(sarayaProperties).values(value as typeof sarayaProperties.$inferInsert).returning(); await tx.insert(sarayaPropertyMemberships).values({ propertyId: property.id, userId: actorUserId, role: "super_admin" }); return property; }); }
async function createPropertyForOwner(value: Record<string, unknown>, actorUserId: string) { return db.transaction(async (tx) => { const [user] = await tx.select({ displayNameAr: sarayaUsers.displayNameAr, displayNameEn: sarayaUsers.displayNameEn }).from(sarayaUsers).where(and(eq(sarayaUsers.id, actorUserId), eq(sarayaUsers.isActive, true))).limit(1); if (!user) throw new Error("SARAYA_OWNER_USER_NOT_FOUND"); const [property] = await tx.insert(sarayaProperties).values(value as typeof sarayaProperties.$inferInsert).returning(); const [owner] = await tx.insert(sarayaOwners).values({ propertyId: property.id, userId: actorUserId, nameAr: user.displayNameAr, nameEn: user.displayNameEn }).returning({ id: sarayaOwners.id }); await tx.insert(sarayaPropertyMemberships).values({ propertyId: property.id, userId: actorUserId, role: "owner" }); return { ...property, ownerId: owner.id }; }); }
async function update(resource: Resource, propertyId: string, id: string, value: Record<string, unknown>) { const patch = { ...value, updatedAt: new Date() }; const rows = resource === "properties" ? await db.update(sarayaProperties).set(patch).where(and(eq(sarayaProperties.id, id), eq(sarayaProperties.id, propertyId))).returning() : resource === "units" ? await db.update(sarayaUnits).set(patch).where(and(eq(sarayaUnits.propertyId, propertyId), eq(sarayaUnits.id, id))).returning() : resource === "tenants" ? await db.update(sarayaTenantOrganizations).set(patch).where(and(eq(sarayaTenantOrganizations.propertyId, propertyId), eq(sarayaTenantOrganizations.id, id))).returning() : resource === "owners" ? await db.update(sarayaOwners).set(patch).where(and(eq(sarayaOwners.propertyId, propertyId), eq(sarayaOwners.id, id))).returning() : await db.update(sarayaPropertyMemberships).set(patch).where(and(eq(sarayaPropertyMemberships.propertyId, propertyId), eq(sarayaPropertyMemberships.id, id))).returning(); return rows[0] ?? null; }
async function updateOwnedUnit(propertyId: string, id: string, ownerId: string, value: Record<string, unknown>) { return db.transaction(async (tx) => { const locked = await tx.execute(sql`SELECT id FROM saraya_units WHERE property_id=${propertyId} AND id=${id} AND owner_id=${ownerId} FOR UPDATE`); if (!(locked as unknown[])[0]) return null; const rows = await tx.update(sarayaUnits).set({ ...value, updatedAt: new Date() }).where(and(eq(sarayaUnits.propertyId, propertyId), eq(sarayaUnits.id, id), eq(sarayaUnits.ownerId, ownerId))).returning(); return rows[0] ?? null; }); }
async function remove(resource: Resource, propertyId: string, id: string) { if (resource === "owners") return false; const rows = resource === "properties" ? await db.update(sarayaProperties).set({ isActive: false, updatedAt: new Date() }).where(and(eq(sarayaProperties.id, propertyId), eq(sarayaProperties.id, id))).returning({ id: sarayaProperties.id }) : resource === "units" ? await db.update(sarayaUnits).set({ status: "inactive", updatedAt: new Date() }).where(and(eq(sarayaUnits.propertyId, propertyId), eq(sarayaUnits.id, id))).returning({ id: sarayaUnits.id }) : resource === "tenants" ? await db.update(sarayaTenantOrganizations).set({ isActive: false, updatedAt: new Date() }).where(and(eq(sarayaTenantOrganizations.propertyId, propertyId), eq(sarayaTenantOrganizations.id, id))).returning({ id: sarayaTenantOrganizations.id }) : await db.update(sarayaPropertyMemberships).set({ isActive: false, updatedAt: new Date() }).where(and(eq(sarayaPropertyMemberships.propertyId, propertyId), eq(sarayaPropertyMemberships.id, id))).returning({ id: sarayaPropertyMemberships.id }); return rows.length > 0; }
async function findActiveUserIdByIdentity(email: string | null, phone: string | null) { const [user] = await db.select({ id: sarayaUsers.id }).from(sarayaUsers).where(and(eq(sarayaUsers.isActive, true), email ? eq(sarayaUsers.normalizedEmail, email) : eq(sarayaUsers.normalizedPhone, phone!))).limit(1); return user?.id ?? null; }
export const propertyManagementRepository: ManagementRepository = { list, get, create, createPropertyForAdmin, createPropertyForOwner, update, updateOwnedUnit, remove, findActiveUserIdByIdentity, async referenceExists(resource, propertyId, id) { const rows = resource === "owner" ? await db.select({ id: sarayaOwners.id }).from(sarayaOwners).where(and(eq(sarayaOwners.propertyId, propertyId), eq(sarayaOwners.id, id))).limit(1) : await db.select({ id: sarayaUnitTypes.id }).from(sarayaUnitTypes).where(and(eq(sarayaUnitTypes.propertyId, propertyId), eq(sarayaUnitTypes.id, id))).limit(1); return rows.length > 0; }, async unitNumberExists(propertyId, unitNumber, excludingId) { const [row] = await db.select({ id: sarayaUnits.id }).from(sarayaUnits).where(and(eq(sarayaUnits.propertyId, propertyId), eq(sarayaUnits.unitNumber, unitNumber), excludingId ? ne(sarayaUnits.id, excludingId) : undefined)).limit(1); return Boolean(row); } };
