import type { SarayaRole } from "@/lib/db/saraya-schema";
import { authorize, authorizeRoleGrant } from "../access/authorize";
import { ApiError, validatedIdentity, type SarayaPermission, type SarayaPrincipal } from "../auth/contracts";
export type Resource = "properties" | "units" | "tenants" | "owners" | "staff";
export interface Cursor { createdAt: string; id: string }
export interface ListInput { cursor?: string; limit?: number; search?: string; status?: string; role?: string }
export interface RepositoryQuery { cursor?: Cursor; limit: number; search?: string; status?: string; role?: string; ownerId?: string }
export interface ManagementRepository { list(r: Resource,p:string,q:RepositoryQuery):Promise<unknown[]>; get(r:Resource,p:string,id:string):Promise<unknown|null>; create(r:Exclude<Resource,"properties">,v:Record<string,unknown>):Promise<unknown>; createPropertyForAdmin(v:Record<string,unknown>,actor:string):Promise<unknown>; createPropertyForOwner(v:Record<string,unknown>,actor:string):Promise<unknown>; update(r:Resource,p:string,id:string,v:Record<string,unknown>):Promise<unknown|null>; updateOwnedUnit(p:string,id:string,ownerId:string,v:Record<string,unknown>):Promise<unknown|null>; remove(r:Resource,p:string,id:string):Promise<boolean>; unitNumberExists(p:string,n:string,x?:string):Promise<boolean>; referenceExists(r:"owner"|"unitType",p:string,id:string):Promise<boolean>; findActiveUserIdByIdentity(email:string|null,phone:string|null):Promise<string|null> }
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const roles:SarayaRole[]=["super_admin","property_manager","accountant","maintenance","owner","tenant"];
const statuses=["vacant","occupied","reserved","maintenance","inactive"];
const spec:Record<Resource,{create:string[];update:string[];required:string[]}>= { properties:{create:["code","nameAr","nameEn","addressAr","addressEn","timezone","currencyCode","isActive","rentalApprovalMode"],update:["code","nameAr","nameEn","addressAr","addressEn","timezone","currencyCode","isActive","rentalApprovalMode"],required:["code","nameAr","nameEn"]}, units:{create:["unitTypeId","ownerId","unitNumber","floor","status","areaSquareMeters","marketRent","availableFrom","rentalApprovalOverride"],update:["unitTypeId","ownerId","unitNumber","floor","status","areaSquareMeters","marketRent","availableFrom","rentalApprovalOverride"],required:["unitNumber"]}, tenants:{create:["nameAr","nameEn","registrationNumber","taxNumber","isActive"],update:["nameAr","nameEn","registrationNumber","taxNumber","isActive"],required:["nameAr","nameEn"]}, owners:{create:["nameAr","nameEn","registrationNumber"],update:["nameAr","nameEn","registrationNumber"],required:["nameAr","nameEn"]}, staff:{create:["identity","role","isActive"],update:["role","isActive"],required:["identity","role"]} };
const invalid=(code:string,field?:string)=>new ApiError(422,code,"بيانات الطلب غير صالحة","Invalid request data",field?{[field]:[code]}:undefined);
const str=(v:unknown,f:string,max=255)=>{if(typeof v!=="string"||!v.trim()||v.trim().length>max)throw invalid("INVALID_FIELD",f);return v.trim()};
const validDate=(value:string)=>{const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);if(!match)return false;const date=new Date(Date.UTC(Number(match[1]),Number(match[2])-1,Number(match[3])));return date.toISOString().slice(0,10)===value};
function dto(r:Resource,m:"create"|"update",v:Record<string,unknown>){const s=spec[r];const bad=Object.keys(v).find(k=>!s[m].includes(k));if(bad)throw invalid("UNKNOWN_FIELD",bad);if(m==="create")for(const k of s.required)if(v[k]===undefined)throw invalid("REQUIRED",k);const o:Record<string,unknown>={};for(const[k,x]of Object.entries(v)){if(["nameAr","nameEn","code","unitNumber","timezone"].includes(k))o[k]=str(x,k,k==="unitNumber"?64:255);else if(k==="identity")o[k]=str(x,k,254);else if(["addressAr","addressEn","floor","registrationNumber","taxNumber"].includes(k)){if(x!==null&&x!==undefined)o[k]=str(x,k);else o[k]=x}else if(k==="isActive"){if(typeof x!=="boolean")throw invalid("INVALID_FIELD",k);o[k]=x}else if(["userId","ownerId","unitTypeId"].includes(k)){if(x!==null&&(typeof x!=="string"||!uuid.test(x)))throw invalid("INVALID_UUID",k);o[k]=x}else if(k==="role"){if(typeof x!=="string"||!roles.includes(x as SarayaRole))throw invalid("INVALID_ROLE",k);o[k]=x}else if(k==="status"){if(typeof x!=="string"||!statuses.includes(x))throw invalid("INVALID_STATUS",k);o[k]=x}else if(k==="rentalApprovalMode"){if(x!=="instant"&&x!=="owner_review")throw invalid("INVALID_RENTAL_APPROVAL_MODE",k);o[k]=x}else if(k==="rentalApprovalOverride"){if(x!==null&&x!=="instant"&&x!=="owner_review")throw invalid("INVALID_RENTAL_APPROVAL_MODE",k);o[k]=x}else if(["areaSquareMeters","marketRent"].includes(k)){if(x!==null&&(typeof x!=="string"||!/^\d{1,11}(\.\d{1,3})?$/.test(x)||k==="areaSquareMeters"&&Number(x)<=0))throw invalid("INVALID_DECIMAL",k);o[k]=x}else if(k==="availableFrom"){if(x!==null&&(typeof x!=="string"||!validDate(x)))throw invalid("INVALID_DATE",k);o[k]=x}else if(k==="currencyCode"){const c=str(x,k,3).toUpperCase();if(!/^[A-Z]{3}$/.test(c))throw invalid("INVALID_CURRENCY",k);o[k]=c}}if(!Object.keys(o).length)throw invalid("EMPTY_UPDATE");return o}
export const encodeCursor=(c:Cursor)=>Buffer.from(JSON.stringify(c)).toString("base64url");
export function decodeCursor(v:string){try{const c=JSON.parse(Buffer.from(v,"base64url").toString()) as Cursor;if(!uuid.test(c.id)||Number.isNaN(Date.parse(c.createdAt)))throw 0;return c}catch{throw invalid("INVALID_CURSOR")}}
const rp=(r:Resource):SarayaPermission=>r==="staff"?"memberships:write":r==="tenants"||r==="owners"?"tenants:read":"units:read";
const wp=(r:Resource):SarayaPermission=>r==="staff"?"memberships:write":r==="tenants"||r==="owners"?"tenants:write":"units:write";
export function createPropertyManagementService(repo:ManagementRepository){return{
 async list(p:SarayaPrincipal,r:Resource,pid:string,i:ListInput){authorize(p,{propertyId:pid,permission:rp(r)});const limit=i.limit??25;if(!Number.isFinite(limit)||!Number.isInteger(limit)||limit<1||limit>100)throw invalid("INVALID_LIMIT","limit");const search=i.search?.trim();if(search&&search.length>100)throw invalid("INVALID_SEARCH","search");if(i.status&&(r==="units"?!statuses.includes(i.status):r==="tenants"?!["active","inactive"].includes(i.status):true))throw invalid("INVALID_STATUS","status");if(i.role&&(r!=="staff"||!roles.includes(i.role as SarayaRole)))throw invalid("INVALID_ROLE","role");const m=p.memberships.find(x=>x.propertyId===pid);const items=await repo.list(r,pid,{limit,...(i.cursor?{cursor:decodeCursor(i.cursor)}:{}),...(search?{search:search.replace(/[\\%_]/g,"\\$&")} :{}),...(i.status?{status:i.status}:{}),...(i.role?{role:i.role}:{}),...(r==="units"&&m?.role==="owner"&&m.ownerId?{ownerId:m.ownerId}:{})});const page=items.slice(0,limit),last=page.at(-1)as{id?:string;createdAt?:Date|string}|undefined;return{items:page,nextCursor:items.length>limit&&last?.id&&last.createdAt?encodeCursor({id:last.id,createdAt:new Date(last.createdAt).toISOString()}):null}},
 async get(p:SarayaPrincipal,r:Resource,pid:string,id:string){if(!uuid.test(id))throw invalid("INVALID_UUID","id");const m=p.memberships.find(x=>x.propertyId===pid);if(r==="tenants"&&m?.role==="tenant")authorize(p,{propertyId:pid,permission:"tenant:self:read",tenantId:id});else if(r==="owners"&&m?.role==="owner")authorize(p,{propertyId:pid,permission:"owner:self:read",ownerId:id});else authorize(p,{propertyId:pid,permission:rp(r)});const item=await repo.get(r,pid,id);if(!item||r==="units"&&m?.role==="owner"&&(item as{ownerId?:string}).ownerId!==m.ownerId)throw new ApiError(404,"NOT_FOUND","السجل غير موجود","Record not found");return item},
 async create(p:SarayaPrincipal,r:Resource,pid:string,v:Record<string,unknown>){if(r==="properties"){const safe=dto(r,"create",v);if(p.memberships.some(x=>x.role==="super_admin"))return repo.createPropertyForAdmin(safe,p.userId);if(p.memberships.some(x=>x.role==="owner"))return repo.createPropertyForOwner(safe,p.userId);throw new ApiError(403,"PERMISSION_DENIED","ليست لديك الصلاحية المطلوبة","Permission denied")}authorize(p,{propertyId:pid,permission:wp(r)});const safe=dto(r,"create",v);const membership=p.memberships.find(x=>x.propertyId===pid)!;if(r==="staff"){authorizeRoleGrant(membership.role,safe.role as SarayaRole);let normalized:{email:string|null;phone:string|null};try{normalized=validatedIdentity(safe.identity as string)}catch(error){if(error instanceof ApiError)throw new ApiError(error.status,error.code,error.messageAr,error.messageEn,{identity:Object.values(error.fieldErrors??{}).flat()});throw error}const userId=await repo.findActiveUserIdByIdentity(normalized.email,normalized.phone);if(!userId)throw new ApiError(404,"STAFF_USER_NOT_FOUND","لم يتم العثور على مستخدم نشط بهذه الهوية","No active user was found for this identity");delete safe.identity;safe.userId=userId}if(r==="units"){if(membership.role==="owner"){if(!membership.ownerId)throw new ApiError(403,"OWNER_SCOPE_REQUIRED","حساب المالك غير مرتبط بمالك العقار","Owner account is not linked to a property owner");safe.ownerId=membership.ownerId}if(await repo.unitNumberExists(pid,safe.unitNumber as string))throw new ApiError(409,"UNIT_NUMBER_EXISTS","رقم الوحدة مستخدم","Unit number already exists");for(const[f,k]of[["ownerId","owner"],["unitTypeId","unitType"]]as const)if(safe[f]&&!await repo.referenceExists(k,pid,safe[f]as string))throw invalid("CROSS_PROPERTY_REFERENCE",f)}return repo.create(r,{...safe,propertyId:pid})},
 async update(p:SarayaPrincipal,r:Resource,pid:string,id:string,v:Record<string,unknown>){authorize(p,{propertyId:pid,permission:wp(r)});const membership=p.memberships.find(x=>x.propertyId===pid)!;if(r==="properties"&&Object.hasOwn(v,"rentalApprovalMode")&&membership.role!=="super_admin")throw new ApiError(403,"PROPERTY_APPROVAL_MODE_ACCESS_DENIED","تعديل سياسة الموافقة العامة متاح للمشرف العام فقط","Only a super admin can change the property approval policy");if(r==="units"&&membership.role==="owner"&&Object.hasOwn(v,"ownerId"))throw invalid("UNKNOWN_FIELD","ownerId");const safe=dto(r,"update",v);if(r==="staff"){const current=await repo.get(r,pid,id);if(!current)throw new ApiError(404,"NOT_FOUND","السجل غير موجود","Record not found");const actor=membership.role;authorizeRoleGrant(actor,(current as{role:SarayaRole}).role);if(safe.role)authorizeRoleGrant(actor,safe.role as SarayaRole)}if(r==="units"){if(safe.unitNumber&&await repo.unitNumberExists(pid,safe.unitNumber as string,id))throw new ApiError(409,"UNIT_NUMBER_EXISTS","رقم الوحدة مستخدم","Unit number already exists");for(const[f,k]of[["ownerId","owner"],["unitTypeId","unitType"]]as const)if(safe[f]&&!await repo.referenceExists(k,pid,safe[f]as string))throw invalid("CROSS_PROPERTY_REFERENCE",f);if(membership.role==="owner"){if(!membership.ownerId)throw new ApiError(403,"OWNER_SCOPE_REQUIRED","حساب المالك غير مرتبط بمالك العقار","Owner account is not linked to a property owner");const owned=await repo.updateOwnedUnit(pid,id,membership.ownerId,safe);if(!owned)throw new ApiError(409,"UNIT_OWNER_CHANGED","تم تغيير مالك الوحدة، أعد تحميل البيانات","The unit owner changed; refresh and try again");return owned}}const x=await repo.update(r,pid,id,safe);if(!x)throw new ApiError(404,"NOT_FOUND","السجل غير موجود","Record not found");return x},
 async remove(p:SarayaPrincipal,r:Resource,pid:string,id:string){authorize(p,{propertyId:pid,permission:wp(r)});const membership=p.memberships.find(x=>x.propertyId===pid)!;if(r==="units"&&membership.role==="owner"){const current=await repo.get(r,pid,id);if(!current||(current as{ownerId?:string}).ownerId!==membership.ownerId)throw new ApiError(404,"NOT_FOUND","السجل غير موجود","Record not found")}if(r==="owners")throw new ApiError(409,"OWNER_ARCHIVE_UNSUPPORTED","أرشفة المالك غير متاحة حاليًا","Owner archiving is not currently supported");if(r==="staff"){const current=await repo.get(r,pid,id);if(!current)throw new ApiError(404,"NOT_FOUND","السجل غير موجود","Record not found");authorizeRoleGrant(membership.role,(current as{role:SarayaRole}).role)}if(!await repo.remove(r,pid,id))throw new ApiError(404,"NOT_FOUND","السجل غير موجود","Record not found")}
}}
