DO $$
DECLARE missing text;
BEGIN
  SELECT string_agg(name, ', ') INTO missing FROM (VALUES ('saraya_leases'), ('saraya_lease_versions'), ('saraya_rent_schedule_items'), ('saraya_lease_events')) expected(name) WHERE to_regclass('public.' || name) IS NULL;
  IF missing IS NOT NULL THEN RAISE EXCEPTION 'Missing Saraya lease tables: %', missing; END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conname='saraya_units_property_id_key' AND c.contype='u' AND c.conrelid='public.saraya_units'::regclass AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY k(attnum,ord) JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.attnum ORDER BY k.ord)=ARRAY['property_id', 'id']) THEN RAISE EXCEPTION 'Missing scoped unit unique key'; END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conname='saraya_leases_property_unit_fk' AND c.contype='f' AND c.conrelid = 'public.saraya_leases'::regclass AND c.confrelid = 'public.saraya_units'::regclass AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY k(attnum,ord) JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.attnum ORDER BY k.ord)=ARRAY['property_id', 'unit_id'] AND ARRAY(SELECT a.attname::text FROM unnest(c.confkey) WITH ORDINALITY k(attnum,ord) JOIN pg_attribute a ON a.attrelid=c.confrelid AND a.attnum=k.attnum ORDER BY k.ord)=ARRAY['property_id', 'id']) THEN RAISE EXCEPTION 'Invalid scoped unit foreign key'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conname='saraya_leases_property_tenant_fk' AND c.contype='f' AND c.conrelid='public.saraya_leases'::regclass AND c.confrelid='public.saraya_tenant_organizations'::regclass AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY k(attnum,ord) JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.attnum ORDER BY k.ord)=ARRAY['property_id', 'tenant_organization_id'] AND ARRAY(SELECT a.attname::text FROM unnest(c.confkey) WITH ORDINALITY k(attnum,ord) JOIN pg_attribute a ON a.attrelid=c.confrelid AND a.attnum=k.attnum ORDER BY k.ord)=ARRAY['property_id', 'id']) THEN RAISE EXCEPTION 'Invalid scoped tenant foreign key'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conname='saraya_lease_versions_property_lease_fk' AND c.contype='f' AND c.conrelid='public.saraya_lease_versions'::regclass AND c.confrelid='public.saraya_leases'::regclass AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY k(attnum,ord) JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.attnum ORDER BY k.ord)=ARRAY['property_id', 'lease_id'] AND ARRAY(SELECT a.attname::text FROM unnest(c.confkey) WITH ORDINALITY k(attnum,ord) JOIN pg_attribute a ON a.attrelid=c.confrelid AND a.attnum=k.attnum ORDER BY k.ord)=ARRAY['property_id', 'id']) THEN RAISE EXCEPTION 'Invalid scoped lease version foreign key'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conname='saraya_leases_current_version_fk' AND c.contype='f' AND c.conrelid='public.saraya_leases'::regclass AND c.confrelid='public.saraya_lease_versions'::regclass AND c.condeferrable AND c.condeferred AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY k(attnum,ord) JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.attnum ORDER BY k.ord)=ARRAY['property_id', 'id', 'current_version'] AND ARRAY(SELECT a.attname::text FROM unnest(c.confkey) WITH ORDINALITY k(attnum,ord) JOIN pg_attribute a ON a.attrelid=c.confrelid AND a.attnum=k.attnum ORDER BY k.ord)=ARRAY['property_id', 'lease_id', 'version']) THEN RAISE EXCEPTION 'Invalid deferred current version foreign key'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conname='saraya_rent_schedule_property_version_fk' AND c.contype='f' AND c.conrelid='public.saraya_rent_schedule_items'::regclass AND c.confrelid='public.saraya_lease_versions'::regclass AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY k(attnum,ord) JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.attnum ORDER BY k.ord)=ARRAY['property_id', 'lease_id', 'lease_version_id'] AND ARRAY(SELECT a.attname::text FROM unnest(c.confkey) WITH ORDINALITY k(attnum,ord) JOIN pg_attribute a ON a.attrelid=c.confrelid AND a.attnum=k.attnum ORDER BY k.ord)=ARRAY['property_id', 'lease_id', 'id']) THEN RAISE EXCEPTION 'Invalid scoped schedule version foreign key'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conname='saraya_lease_events_property_lease_fk' AND c.contype='f' AND c.conrelid='public.saraya_lease_events'::regclass AND c.confrelid='public.saraya_leases'::regclass AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY k(attnum,ord) JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.attnum ORDER BY k.ord)=ARRAY['property_id', 'lease_id'] AND ARRAY(SELECT a.attname::text FROM unnest(c.confkey) WITH ORDINALITY k(attnum,ord) JOIN pg_attribute a ON a.attrelid=c.confrelid AND a.attnum=k.attnum ORDER BY k.ord)=ARRAY['property_id', 'id']) THEN RAISE EXCEPTION 'Invalid lease event parent foreign key'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conname='saraya_lease_events_actor_user_fk' AND c.contype='f' AND c.conrelid='public.saraya_lease_events'::regclass AND c.confrelid='public.saraya_users'::regclass AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY k(attnum,ord) JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.attnum ORDER BY k.ord)=ARRAY['actor_user_id'] AND ARRAY(SELECT a.attname::text FROM unnest(c.confkey) WITH ORDINALITY k(attnum,ord) JOIN pg_attribute a ON a.attrelid=c.confrelid AND a.attnum=k.attnum ORDER BY k.ord)=ARRAY['id']) THEN RAISE EXCEPTION 'Invalid lease event actor foreign key'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid='public.saraya_lease_versions'::regclass AND tgname='saraya_lease_versions_immutable' AND NOT tgisinternal) THEN RAISE EXCEPTION 'Missing immutable version trigger'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid='public.saraya_rent_schedule_items'::regclass AND tgname='saraya_rent_schedule_immutable' AND NOT tgisinternal) THEN RAISE EXCEPTION 'Missing immutable schedule trigger'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid='public.saraya_lease_events'::regclass AND tgname='saraya_lease_events_immutable' AND NOT tgisinternal) THEN RAISE EXCEPTION 'Missing immutable event trigger'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_index ix JOIN pg_class i ON i.oid=ix.indexrelid WHERE ix.indrelid='public.saraya_rent_schedule_items'::regclass AND i.relname='saraya_rent_schedule_property_due_idx' AND ARRAY(SELECT a.attname::text FROM unnest(ix.indkey) WITH ORDINALITY k(attnum,ord) JOIN pg_attribute a ON a.attrelid=ix.indrelid AND a.attnum=k.attnum ORDER BY k.ord)=ARRAY['property_id', 'due_date']) THEN RAISE EXCEPTION 'Invalid schedule due index'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_index ix JOIN pg_class i ON i.oid=ix.indexrelid WHERE ix.indrelid='public.saraya_lease_events'::regclass AND i.relname='saraya_lease_events_property_lease_created_idx' AND ARRAY(SELECT a.attname::text FROM unnest(ix.indkey) WITH ORDINALITY k(attnum,ord) JOIN pg_attribute a ON a.attrelid=ix.indrelid AND a.attnum=k.attnum ORDER BY k.ord)=ARRAY['property_id', 'lease_id', 'created_at']) THEN RAISE EXCEPTION 'Invalid lease event history index'; END IF;
END $$;
