"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, KeyRound, Loader2, Pencil, Plus, Search, ShieldCheck, UserCheck, UserRoundCog, UserX, X } from "lucide-react";
import { Link } from "@/i18n/navigation";
import AdminLogoutButton from "@/components/admin/AdminLogoutButton";
import { ADMIN_PERMISSION_KEYS, type AdminPermission, type AdminPermissions } from "@/lib/auth/admin-permissions";

type AdminRow = { id: string; fullName: string; email: string; role: "super_admin" | "admin" | "reviewer"; isActive: boolean; permissions: AdminPermissions; lastLoginAt: string | null; createdAt: string };
type FormState = { fullName: string; email: string; password: string; role: "admin" | "super_admin"; isActive: boolean; permissions: AdminPermissions };
const emptyForm: FormState = { fullName: "", email: "", password: "", role: "admin", isActive: true, permissions: {} };
const inputClass = "h-12 w-full rounded-xl border border-gray-200 bg-white px-4 text-sm font-bold text-[#082B67] outline-none transition placeholder:text-gray-400 focus:border-[#006C32] focus:ring-4 focus:ring-primary-light";

const permissionLabels: Record<AdminPermission, { ar: string; en: string }> = {
  view_dashboard: { ar: "عرض لوحة التحكم", en: "View dashboard" }, manage_admins: { ar: "إدارة الأدمن", en: "Manage admins" },
  manage_discounts: { ar: "إدارة أكواد الخصم", en: "Manage discount codes" }, manage_approvals: { ar: "إدارة الموافقات", en: "Manage approvals" },
  manage_requests: { ar: "إدارة الطلبات", en: "Manage requests" }, manage_finance: { ar: "إدارة الحسابات والمالية", en: "Manage finance" },
  manage_reviews: { ar: "إدارة التقييمات", en: "Manage reviews" }, manage_lawyers: { ar: "إدارة المحامين", en: "Manage lawyers" },
};

export default function AdminUsersContent({ isAr }: { isAr: boolean }) {
  const [admins, setAdmins] = useState<AdminRow[]>([]); const [form, setForm] = useState<FormState>(emptyForm);
  const [editingId, setEditingId] = useState<string | null>(null); const [busy, setBusy] = useState(true); const [saving, setSaving] = useState(false);
  const [search, setSearch] = useState(""); const [message, setMessage] = useState<{ ok: boolean; text: string } | null>(null);
  const load = useCallback(async () => { const response = await fetch("/api/admin/admin-users", { cache: "no-store" }); const data = await response.json().catch(() => ({})); if (response.ok) setAdmins(data.admins ?? []); else setMessage({ ok: false, text: isAr ? "تعذر تحميل حسابات الأدمن." : "Could not load admin accounts." }); setBusy(false); }, [isAr]);
  useEffect(() => {
    let active = true;
    fetch("/api/admin/admin-users", { cache: "no-store" })
      .then(async (response) => ({ response, data: await response.json().catch(() => ({})) }))
      .then(({ response, data }) => {
        if (!active) return;
        if (response.ok) setAdmins(data.admins ?? []);
        else setMessage({ ok: false, text: isAr ? "تعذر تحميل حسابات الأدمن." : "Could not load admin accounts." });
        setBusy(false);
      });
    return () => { active = false; };
  }, [isAr]);
  const visible = useMemo(() => { const query = search.trim().toLowerCase(); return query ? admins.filter((admin) => `${admin.fullName} ${admin.email}`.toLowerCase().includes(query)) : admins; }, [admins, search]);
  const startEdit = (admin: AdminRow) => { setEditingId(admin.id); setForm({ fullName: admin.fullName, email: admin.email, password: "", role: admin.role === "super_admin" ? "super_admin" : "admin", isActive: admin.isActive, permissions: admin.permissions ?? {} }); setMessage(null); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const reset = () => { setEditingId(null); setForm(emptyForm); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setMessage(null); const response = await fetch(editingId ? `/api/admin/admin-users/${editingId}` : "/api/admin/admin-users", { method: editingId ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json().catch(() => ({})); if (response.ok) { setMessage({ ok: true, text: isAr ? (editingId ? "تم تحديث حساب الأدمن." : "تمت إضافة الأدمن بنجاح.") : (editingId ? "Admin updated." : "Admin added successfully.") }); reset(); await load(); } else { const errors: Record<string, string> = { duplicate_email: isAr ? "البريد مستخدم مسبقًا." : "Email already exists.", weak_password: isAr ? "كلمة المرور يجب أن تكون 10 أحرف وتحتوي أحرفًا وأرقامًا." : "Password must be 10+ characters with letters and numbers.", cannot_disable_self: isAr ? "لا يمكنك تعطيل حسابك الحالي." : "You cannot disable your current account.", cannot_change_own_role: isAr ? "لا يمكنك خفض صلاحية حسابك الحالي." : "You cannot demote your current account.", last_super_admin: isAr ? "يجب أن يبقى Super Admin نشط واحد على الأقل." : "At least one active super admin must remain." }; setMessage({ ok: false, text: errors[data.error] ?? (isAr ? "تعذر حفظ الحساب." : "Could not save account.") }); } setSaving(false); };
  const disable = async (admin: AdminRow) => { if (!confirm(isAr ? `تعطيل حساب ${admin.fullName}؟` : `Disable ${admin.fullName}?`)) return; const response = await fetch(`/api/admin/admin-users/${admin.id}`, { method: "DELETE" }); const data = await response.json().catch(() => ({})); if (response.ok) { setMessage({ ok: true, text: isAr ? "تم تعطيل الحساب." : "Account disabled." }); await load(); } else setMessage({ ok: false, text: data.error === "cannot_disable_self" ? (isAr ? "لا يمكنك تعطيل حسابك الحالي." : "You cannot disable your account.") : (isAr ? "تعذر تعطيل الحساب." : "Could not disable account.") }); };
  const togglePermission = (key: AdminPermission) => { if (key === "manage_admins") return; setForm((current) => ({ ...current, permissions: { ...current.permissions, [key]: !current.permissions[key] } })); };

  return <main className="min-h-screen bg-[#F7F8FA] px-5 py-10" dir={isAr ? "rtl" : "ltr"}><div className="mx-auto max-w-7xl">
    <div className="mb-4 flex items-center justify-between gap-3"><Link href="/admin" className="inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-sm font-extrabold text-[#082B67] shadow-sm hover:border-[#006C32]/30 hover:text-[#006C32]"><ArrowLeft className="h-4 w-4 rtl:rotate-180" />{isAr ? "لوحة التحكم" : "Dashboard"}</Link><AdminLogoutButton /></div>
    <section className="mb-6 overflow-hidden rounded-3xl bg-[linear-gradient(135deg,#006C32_0%,#005126_100%)] p-7 text-white shadow-[0_22px_60px_rgba(0,108,50,0.24)]"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-white/12"><ShieldCheck /></div><h1 className="text-2xl font-black sm:text-3xl">{isAr ? "إدارة الأدمن والصلاحيات" : "Admins & Permissions"}</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-white/75">{isAr ? "أضف حسابات الإدارة وحدد بدقة الصفحات والعمليات المسموحة لكل حساب." : "Add admin accounts and precisely control the pages and operations each account can access."}</p></div><div className="rounded-2xl bg-white/10 px-5 py-3 text-center"><p className="text-3xl font-black">{admins.filter((a) => a.isActive).length}</p><p className="text-xs font-bold text-white/70">{isAr ? "حساب نشط" : "Active accounts"}</p></div></div></section>
    {message ? <div className={`mb-5 rounded-2xl border px-4 py-3 text-sm font-bold ${message.ok ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-red-200 bg-red-50 text-red-700"}`}>{message.text}</div> : null}
    <div className="grid gap-6 lg:grid-cols-[390px_1fr]">
      <form onSubmit={submit} className="h-fit rounded-3xl border border-gray-100 bg-white p-6 shadow-[0_18px_50px_rgba(7,17,31,0.07)]"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-black text-[#082B67]">{editingId ? (isAr ? "تعديل الأدمن" : "Edit admin") : (isAr ? "إضافة أدمن جديد" : "Add new admin")}</h2><p className="mt-1 text-xs text-gray-500">{isAr ? "كل الصلاحيات تُراجع من السيرفر." : "All permissions are enforced server-side."}</p></div>{editingId ? <button type="button" onClick={reset} className="rounded-xl bg-gray-100 p-2 text-gray-500"><X className="h-4 w-4" /></button> : <Plus className="text-[#006C32]" />}</div>
        <div className="space-y-4"><label className="block text-sm font-extrabold text-[#082B67]">{isAr ? "الاسم الكامل" : "Full name"}<input required className={`${inputClass} mt-2`} value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} /></label><label className="block text-sm font-extrabold text-[#082B67]">{isAr ? "البريد الإلكتروني" : "Email"}<input required type="email" className={`${inputClass} mt-2`} value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label className="block text-sm font-extrabold text-[#082B67]">{isAr ? "نوع الحساب" : "Account type"}<select className={`${inputClass} mt-2`} value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value as "admin" | "super_admin" })}><option value="admin">Admin</option><option value="super_admin">Super Admin</option></select><span className="mt-1.5 block text-[11px] leading-5 text-gray-400">{form.role === "super_admin" ? (isAr ? "يمتلك جميع الصلاحيات تلقائيًا." : "Automatically has all permissions.") : (isAr ? "حدد الصلاحيات المسموحة أدناه." : "Choose allowed permissions below.")}</span></label><label className="block text-sm font-extrabold text-[#082B67]">{editingId ? (isAr ? "كلمة مرور جديدة (اختياري)" : "New password (optional)") : (isAr ? "كلمة المرور" : "Password")}<div className="relative mt-2"><KeyRound className="absolute start-4 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input required={!editingId} type="password" minLength={editingId ? undefined : 10} className={`${inputClass} ps-11`} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></div></label></div>
        <div className="mt-6"><p className="mb-3 text-sm font-extrabold text-[#082B67]">{isAr ? "الصلاحيات" : "Permissions"}</p><div className="grid gap-2">{ADMIN_PERMISSION_KEYS.map((key) => { const disabled = form.role === "super_admin" || key === "manage_admins"; const checked = form.role === "super_admin" || (!disabled && form.permissions[key] === true); return <button key={key} type="button" disabled={disabled} onClick={() => togglePermission(key)} className={`flex items-center justify-between rounded-xl border px-3 py-2.5 text-start text-xs font-bold transition ${disabled ? "cursor-not-allowed border-gray-100 bg-gray-50 text-gray-400" : checked ? "border-[#006C32]/25 bg-primary-light text-[#006C32]" : "border-gray-200 text-gray-600 hover:border-[#006C32]/30"}`}><span>{isAr ? permissionLabels[key].ar : permissionLabels[key].en}{key === "manage_admins" && form.role !== "super_admin" ? <small className="ms-1 opacity-70">({isAr ? "لـ super_admin فقط" : "super_admin only"})</small> : null}</span><span className={`flex h-5 w-5 items-center justify-center rounded-md border ${checked ? "border-[#006C32] bg-[#006C32] text-white" : "border-gray-300 bg-white"}`}>{checked ? <Check className="h-3.5 w-3.5" /> : null}</span></button>; })}</div></div>
        <button disabled={saving} className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#006C32] text-sm font-extrabold text-white shadow-[0_10px_24px_rgba(0,108,50,0.22)] transition hover:bg-[#005126] disabled:opacity-60">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : editingId ? <Pencil className="h-4 w-4" /> : <Plus className="h-4 w-4" />}{editingId ? (isAr ? "حفظ التعديلات" : "Save changes") : (isAr ? "إضافة الأدمن" : "Add admin")}</button>
      </form>
      <section><div className="mb-4 rounded-2xl border border-gray-100 bg-white p-3 shadow-sm"><div className="relative"><Search className="absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder={isAr ? "بحث بالاسم أو البريد..." : "Search name or email..."} className={`${inputClass} ps-10`} /></div></div>
        {busy ? <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-[#006C32]" /></div> : <div className="grid gap-4">{visible.map((admin) => <article key={admin.id} className="rounded-3xl border border-gray-100 bg-white p-5 shadow-[0_14px_40px_rgba(7,17,31,0.055)]"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div className="flex gap-3"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl ${admin.isActive ? "bg-emerald-50 text-emerald-700" : "bg-gray-100 text-gray-500"}`}>{admin.isActive ? <UserCheck className="h-5 w-5" /> : <UserX className="h-5 w-5" />}</div><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-black text-[#082B67]">{admin.fullName}</h3><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${admin.role === "super_admin" ? "bg-[#082B67] text-white" : "bg-gray-100 text-gray-600"}`}>{admin.role}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${admin.isActive ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{admin.isActive ? (isAr ? "نشط" : "Active") : (isAr ? "معطّل" : "Disabled")}</span></div><p className="mt-1 text-sm text-gray-500">{admin.email}</p><p className="mt-2 text-xs text-gray-400">{isAr ? "آخر دخول:" : "Last login:"} {admin.lastLoginAt ? new Intl.DateTimeFormat(isAr ? "ar-SA" : "en-SA", { dateStyle: "medium", timeStyle: "short" }).format(new Date(admin.lastLoginAt)) : (isAr ? "لم يسجل الدخول" : "Never")}</p></div></div><div className="flex gap-2"><button onClick={() => startEdit(admin)} className="flex items-center gap-2 rounded-xl border border-gray-200 px-3 py-2 text-xs font-extrabold text-[#082B67] hover:border-[#006C32]/30 hover:text-[#006C32]"><Pencil className="h-3.5 w-3.5" />{isAr ? "تعديل" : "Edit"}</button>{admin.isActive ? <button onClick={() => void disable(admin)} className="rounded-xl border border-red-100 bg-red-50 p-2.5 text-red-700" title={isAr ? "تعطيل" : "Disable"}><UserX className="h-4 w-4" /></button> : null}</div></div><div className="mt-4 flex flex-wrap gap-2">{admin.role === "super_admin" ? <span className="rounded-lg bg-[#082B67]/8 px-2.5 py-1.5 text-[11px] font-bold text-[#082B67]">{isAr ? "جميع الصلاحيات" : "All permissions"}</span> : ADMIN_PERMISSION_KEYS.filter((key) => admin.permissions?.[key]).map((key) => <span key={key} className="rounded-lg bg-red-50 px-2.5 py-1.5 text-[11px] font-bold text-[#006C32]">{isAr ? permissionLabels[key].ar : permissionLabels[key].en}</span>)}</div></article>)}{visible.length === 0 ? <div className="rounded-3xl border border-dashed border-gray-200 bg-white py-16 text-center text-sm font-bold text-gray-400"><UserRoundCog className="mx-auto mb-3 h-9 w-9" />{isAr ? "لا توجد حسابات مطابقة." : "No matching accounts."}</div> : null}</div>}
      </section>
    </div>
  </div></main>;
}
