import type { SarayaRole } from "@/lib/db/saraya-schema";
import { ApiError, type SarayaPermission, type SarayaPrincipal } from "../auth/contracts";
const permissions: Record<SarayaRole, readonly SarayaPermission[]> = {
  super_admin: ["units:read", "units:write", "tenants:read", "tenants:write", "tenant:self:read", "owner:self:read", "billing:read", "billing:write", "maintenance:read", "maintenance:write", "memberships:write"],
  property_manager: ["units:read", "units:write", "tenants:read", "tenants:write", "billing:read", "maintenance:read", "maintenance:write", "memberships:write"],
  accountant: ["units:read", "tenants:read", "billing:read", "billing:write"], maintenance: ["units:read", "maintenance:read", "maintenance:write"], owner: ["owner:self:read", "units:read", "units:write", "tenants:read", "tenants:write", "billing:read", "maintenance:read"], tenant: ["tenant:self:read", "billing:read", "maintenance:read", "maintenance:write"],
};
export const permissionsForRole = (role: SarayaRole) => permissions[role];
export function authorizeRoleGrant(actor: SarayaRole, granted: SarayaRole) { if (granted === "super_admin" && actor !== "super_admin") throw new ApiError(403, "ROLE_GRANT_DENIED", "لا يمكنك منح هذا الدور", "Role grant denied"); }
export function authorize(principal: SarayaPrincipal, scope: { propertyId: string; permission: SarayaPermission; tenantId?: string; ownerId?: string }) { const membership = principal.memberships.find((m) => m.propertyId === scope.propertyId); if (!membership) throw new ApiError(403, "PROPERTY_ACCESS_DENIED", "لا تملك صلاحية لهذا العقار", "Property access denied"); if (!permissions[membership.role].includes(scope.permission)) throw new ApiError(403, "PERMISSION_DENIED", "ليست لديك الصلاحية المطلوبة", "Permission denied"); if (scope.permission === "tenant:self:read" && (membership.role !== "tenant" || !scope.tenantId || membership.tenantId !== scope.tenantId)) throw new ApiError(403, "TENANT_ACCESS_DENIED", "لا يمكنك الوصول إلى بيانات مستأجر آخر", "Tenant access denied"); if (scope.permission === "owner:self:read" && (membership.role !== "owner" || !scope.ownerId || membership.ownerId !== scope.ownerId)) throw new ApiError(403, "OWNER_ACCESS_DENIED", "لا يمكنك الوصول إلى بيانات مالك آخر", "Owner access denied"); }
