import "server-only";
import {sqlClient} from "@/lib/db/client";import {buildCountryTableSet,type ActiveCountry} from "@/lib/db/country-tables";import type {AdminActor,ConsultationTypeInput,ConsultationTypeRecord} from "./types";
type Row={id:string;country_code:string;code:string;name_ar:string;name_en:string;price:string;currency_code:string;duration_minutes:number;icon_key:string;sort_order:number;is_active:boolean;archived_at:string|null};
const map=(r:Row):ConsultationTypeRecord=>({id:r.id,countryCode:r.country_code,code:r.code,nameAr:r.name_ar,nameEn:r.name_en,price:Number(r.price).toFixed(3),currencyCode:r.currency_code,durationMinutes:Number(r.duration_minutes),iconKey:r.icon_key,sortOrder:Number(r.sort_order),isActive:r.is_active,archivedAt:r.archived_at});
const table=(c:ActiveCountry)=>buildCountryTableSet(c).consultation_methods;
export async function listAdminConsultationTypes(c:ActiveCountry){const rows=await sqlClient<Row[]>`SELECT id,country_code,code,name_ar,name_en,price,currency_code,duration_minutes,icon_key,sort_order,is_active,archived_at FROM ONLY ${sqlClient(table(c))} WHERE country_code=${c.code} ORDER BY is_active DESC,sort_order,name_en`;return rows.map(map)}
export async function createConsultationType(c:ActiveCountry,input:Required<ConsultationTypeInput>,actor:AdminActor){try{const rows=await sqlClient<Row[]>`INSERT INTO ${sqlClient(table(c))}(country_code,code,name_ar,name_en,price,currency_code,duration_minutes,icon_key,sort_order,is_active,created_by_admin_id,updated_by_admin_id) VALUES(${c.code},${input.code},${input.nameAr},${input.nameEn},${input.price},${input.currencyCode},${input.durationMinutes},${input.iconKey},COALESCE((SELECT max(sort_order)+1 FROM ONLY ${sqlClient(table(c))} WHERE country_code=${c.code}),0),true,${actor.adminId},${actor.adminId}) RETURNING id,country_code,code,name_ar,name_en,price,currency_code,duration_minutes,icon_key,sort_order,is_active,archived_at`;if(!rows[0])throw Error("not_found");return map(rows[0])}catch(e){if(String(e).includes("unique"))throw Error("duplicate_code");throw e}}
export async function updateConsultationType(c:ActiveCountry,id:string,input:ConsultationTypeInput,actor:AdminActor){const rows=await sqlClient<Row[]>`UPDATE ONLY ${sqlClient(table(c))} SET name_ar=${input.nameAr},name_en=${input.nameEn},price=${input.price},currency_code=${input.currencyCode},duration_minutes=${input.durationMinutes},icon_key=${input.iconKey},updated_by_admin_id=${actor.adminId},updated_at=now() WHERE id=${id} AND country_code=${c.code} RETURNING id,country_code,code,name_ar,name_en,price,currency_code,duration_minutes,icon_key,sort_order,is_active,archived_at`;if(!rows[0])throw Error("not_found");return map(rows[0])}
export async function setConsultationTypeArchived(c:ActiveCountry,id:string,archived:boolean,actor:AdminActor){const archivedAt=archived?new Date().toISOString():null;const rows=await sqlClient<Row[]>`UPDATE ONLY ${sqlClient(table(c))} SET is_active=${!archived},archived_at=${archivedAt},archived_by_admin_id=${archived?actor.adminId:null},updated_by_admin_id=${actor.adminId},updated_at=now() WHERE id=${id} AND country_code=${c.code} RETURNING id,country_code,code,name_ar,name_en,price,currency_code,duration_minutes,icon_key,sort_order,is_active,archived_at`;if(!rows[0])throw Error("not_found");return map(rows[0])}
export async function deleteConsultationType(c:ActiveCountry,id:string){const existing=await sqlClient<Array<{is_active:boolean}>>`SELECT is_active FROM ONLY ${sqlClient(table(c))} WHERE id=${id} AND country_code=${c.code}`;if(!existing[0])throw Error("not_found");if(existing[0].is_active)throw Error("archive_before_delete");await sqlClient`DELETE FROM ONLY ${sqlClient(table(c))} WHERE id=${id} AND country_code=${c.code}`;return {id}}
export async function reorderConsultationTypes(c:ActiveCountry,ids:string[],actor:AdminActor){await sqlClient.begin(async tx=>{for(const [sortOrder,id] of ids.entries()){const rows=await tx`UPDATE ONLY ${tx(table(c))} SET sort_order=${sortOrder},updated_by_admin_id=${actor.adminId},updated_at=now() WHERE id=${id} AND country_code=${c.code} AND is_active=true RETURNING id`;if(!rows[0])throw Error("stale_order")}});return {ids}}
