import { randomBytes, randomUUID } from "node:crypto";
import { and, eq, gt, isNull } from "drizzle-orm";
import { sarayaAuthChallenges, sarayaAuthDeliveryAttempts, sarayaRefreshSessions, sarayaUsers } from "@/lib/db/saraya-schema";
import { ApiError, validatedIdentity } from "./contracts";
import { hashOpaqueToken } from "./invitations";
import { hashPassword } from "./passwords";
export interface OtpVerifier { verify(input: { phone: string; code: string; purpose: "activate" | "forgot_password" }): Promise<boolean> }
export interface RecoveryDelivery { send(target: { email?: string; phone?: string }, token: string): Promise<void> }
export function createRecoveryService(deps: { findUser(identity: string): Promise<{ id: string; normalizedEmail: string | null; normalizedPhone: string | null } | null>; save(input: { id: string; userId: string; normalizedEmail: string | null; normalizedPhone: string | null; tokenHash: string; expiresAt: Date }): Promise<void>; recordDelivery?: (input: { id: string; challengeId: string; channel: "email" | "sms"; status: "queued" | "sent" | "failed"; errorCode?: string }) => Promise<void>; delivery: RecoveryDelivery; generateToken?: () => string; now?: () => Date }) { return { async request(identity: string) { const user = await deps.findUser(identity); if (user) { const raw = (deps.generateToken ?? (() => randomBytes(32).toString("base64url")))(); const challengeId = randomUUID(); const attemptId = randomUUID(); const channel = user.normalizedEmail ? "email" as const : "sms" as const; await deps.save({ id: challengeId, userId: user.id, normalizedEmail: user.normalizedEmail, normalizedPhone: user.normalizedPhone, tokenHash: hashOpaqueToken(raw), expiresAt: new Date((deps.now ?? (() => new Date()))().getTime() + 600_000) }); await deps.recordDelivery?.({ id: attemptId, challengeId, channel, status: "queued" }); try { await deps.delivery.send({ ...(user.normalizedEmail ? { email: user.normalizedEmail } : {}), ...(user.normalizedPhone ? { phone: user.normalizedPhone } : {}) }, raw); await deps.recordDelivery?.({ id: attemptId, challengeId, channel, status: "sent" }); } catch { await deps.recordDelivery?.({ id: attemptId, challengeId, channel, status: "failed", errorCode: "delivery_failed" }); } } return { accepted: true as const }; } }; }
export async function createPasswordResetChallenge(identity: string, delivery: RecoveryDelivery) {
  const { db } = await import("@/lib/db/client");
  const { email, phone } = validatedIdentity(identity);
  return createRecoveryService({ findUser: async () => { const [user] = await db.select({ id: sarayaUsers.id, normalizedEmail: sarayaUsers.normalizedEmail, normalizedPhone: sarayaUsers.normalizedPhone }).from(sarayaUsers).where(email ? eq(sarayaUsers.normalizedEmail, email) : eq(sarayaUsers.normalizedPhone, phone!)).limit(1); return user ?? null; }, save: async (input) => { await db.insert(sarayaAuthChallenges).values({ ...input, purpose: "forgot_password" }); }, recordDelivery: async (input) => { if (input.status === "queued") await db.insert(sarayaAuthDeliveryAttempts).values({ id: input.id, challengeId: input.challengeId, channel: input.channel, status: "queued", nextAttemptAt: new Date() }); else await db.update(sarayaAuthDeliveryAttempts).set({ status: input.status, attempts: 1, lastErrorCode: input.errorCode ?? null, nextAttemptAt: input.status === "failed" ? new Date(Date.now() + 60_000) : null, updatedAt: new Date() }).where(eq(sarayaAuthDeliveryAttempts.id, input.id)); }, delivery }).request(identity);
}
export async function resetPassword(token: string, password: string) {
  const { db } = await import("@/lib/db/client");
  const now = new Date(); const tokenHash = hashOpaqueToken(token); const [valid] = await db.select({ id: sarayaAuthChallenges.id, userId: sarayaAuthChallenges.userId }).from(sarayaAuthChallenges).where(and(eq(sarayaAuthChallenges.tokenHash, tokenHash), eq(sarayaAuthChallenges.purpose, "forgot_password"), isNull(sarayaAuthChallenges.consumedAt), gt(sarayaAuthChallenges.expiresAt, now))).limit(1); const userId = valid?.userId; if (!userId) throw new ApiError(410, "CHALLENGE_INVALID_OR_EXPIRED", "الرابط غير صالح أو منتهي", "Challenge is invalid or expired"); const passwordHash = await hashPassword(password); await db.transaction(async (tx) => { const consumed = await tx.update(sarayaAuthChallenges).set({ consumedAt: now }).where(and(eq(sarayaAuthChallenges.id, valid.id), isNull(sarayaAuthChallenges.consumedAt), gt(sarayaAuthChallenges.expiresAt, now))).returning({ id: sarayaAuthChallenges.id }); if (!consumed.length) throw new ApiError(409, "CHALLENGE_USED", "تم استخدام الرابط", "Challenge has already been used"); await tx.update(sarayaUsers).set({ passwordHash, updatedAt: now }).where(eq(sarayaUsers.id, userId)); await tx.update(sarayaRefreshSessions).set({ revokedAt: now }).where(and(eq(sarayaRefreshSessions.userId, userId), isNull(sarayaRefreshSessions.revokedAt))); });
}
