import { describe, expect, it } from "vitest";
import { clearWebSessionCookies, createRateLimiter, parseRefreshRequest, webSessionResponse } from "./security";
describe("Saraya auth edge security", () => {
  it("rate limits independent IP and identity buckets without storing raw values", async () => { const counts = new Map<string, number>(); const limiter = createRateLimiter({ store: { increment: async (key) => { const value = (counts.get(key) ?? 0) + 1; counts.set(key, value); return value; } }, limit: 2, windowMs: 60_000, now: () => new Date(0) }); await limiter.check("login", "1.2.3.4", "A@B.COM"); await limiter.check("login", "1.2.3.4", "a@b.com"); await expect(limiter.check("login", "1.2.3.4", "other@b.com")).rejects.toThrowError(/RATE_LIMITED/); expect([...counts.keys()].join(" ")).not.toContain("a@b.com"); expect([...counts.keys()].some((key) => key.startsWith("login:identity:"))).toBe(true); });
  it("stops before creating identity buckets once the IP is blocked and prunes expired buckets", async () => { const incremented: string[] = []; const pruned: Date[] = []; const limiter = createRateLimiter({ store: { prune: async (before) => void pruned.push(before), increment: async (key) => { incremented.push(key); return key.startsWith("reset:ip:") ? 2 : 1; } }, limit: 1, windowMs: 60_000, now: () => new Date(120_000) }); await expect(limiter.check("reset", "1.2.3.4", "arbitrary-token")).rejects.toThrowError(/RATE_LIMITED/); expect(incremented).toHaveLength(1); expect(incremented[0]).toMatch(/^reset:ip:/); expect(pruned).toEqual([new Date(60_000)]); });
  it("allows native body refresh only with explicit client kind", () => { expect(parseRefreshRequest(new Request("https://x.test", { method: "POST", headers: { "x-saraya-client": "native" } }), { refreshToken: "native-token" })).toEqual({ token: "native-token", web: false }); expect(() => parseRefreshRequest(new Request("https://x.test", { method: "POST", headers: { origin: "https://x.test" } }), { refreshToken: "leak" })).toThrowError(/REFRESH_COOKIE_REQUIRED/); });
  it("requires same-origin and double-submit CSRF for web refresh", () => { const request = new Request("https://x.test/api", { method: "POST", headers: { origin: "https://x.test", cookie: "__Host-saraya_refresh=r; saraya_csrf=c", "x-saraya-csrf": "c" } }); expect(parseRefreshRequest(request, {})).toEqual({ token: "r", web: true }); });
  it("rejects bad origin and mismatched CSRF", () => { expect(() => parseRefreshRequest(new Request("https://x.test/api", { headers: { origin: "https://evil.test", cookie: "__Host-saraya_refresh=r; saraya_csrf=c", "x-saraya-csrf": "c" } }), {})).toThrowError(/ORIGIN_DENIED/); expect(() => parseRefreshRequest(new Request("https://x.test/api", { headers: { origin: "https://x.test", cookie: "__Host-saraya_refresh=r; saraya_csrf=c", "x-saraya-csrf": "x" } }), {})).toThrowError(/CSRF_DENIED/); });
  it("sets secure refresh cookie flags", () => { const response = webSessionResponse({ accessToken: "a", refreshToken: "r" }); expect(response.headers.get("set-cookie")).toContain("__Host-saraya_refresh=r"); expect(response.headers.get("set-cookie")).toContain("HttpOnly"); expect(response.headers.get("set-cookie")).toContain("Secure"); expect(response.headers.get("set-cookie")).toContain("SameSite=Strict"); });
  it("clears both web session cookies", () => { const cookies = clearWebSessionCookies().headers.get("set-cookie"); expect(cookies).toContain("__Host-saraya_refresh="); expect(cookies).toContain("saraya_csrf="); expect(cookies).toContain("Max-Age=0"); });
});
