import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { ApiError, normalizeEmail } from "./contracts";
export interface AuthRateLimitStore { increment(bucket: string, now: Date, windowMs: number): Promise<number>; prune?(before: Date): Promise<void> }
export function createRateLimiter(options: { store: AuthRateLimitStore; limit: number; windowMs: number; now?: () => Date }) { const now = options.now ?? (() => new Date()); const bucket = (scope: string, value: string) => `${scope}:${createHash("sha256").update(value).digest("hex")}`; return { async check(operation: string, ip: string, identity: string) { const at = now(); await options.store.prune?.(new Date(at.getTime() - options.windowMs)); const ipCount = await options.store.increment(bucket(`${operation}:ip`, ip), at, options.windowMs); if (ipCount > options.limit) throw new ApiError(429, "RATE_LIMITED", "محاولات كثيرة، حاول لاحقًا", "Too many attempts, try again later"); const identityCount = await options.store.increment(bucket(`${operation}:identity`, normalizeEmail(identity)), at, options.windowMs); if (identityCount > options.limit) throw new ApiError(429, "RATE_LIMITED", "محاولات كثيرة، حاول لاحقًا", "Too many attempts, try again later"); } }; }
const cookies = (request: Request) => Object.fromEntries((request.headers.get("cookie") ?? "").split(";").map((part) => part.trim().split("=").map(decodeURIComponent)).filter(([key, value]) => key && value));
const same = (a: string, b: string) => { const x = Buffer.from(a); const y = Buffer.from(b); return x.length === y.length && timingSafeEqual(x, y); };
export function parseRefreshRequest(request: Request, body: Record<string, unknown>) { if (request.headers.get("x-saraya-client") === "native") { if (typeof body.refreshToken !== "string" || !body.refreshToken) throw new ApiError(422, "REFRESH_TOKEN_REQUIRED", "رمز التجديد مطلوب", "Refresh token required"); return { token: body.refreshToken, web: false as const }; } const values = cookies(request); const origin = request.headers.get("origin"); const expectedOrigin = new URL(request.url).origin; const headerCsrf = request.headers.get("x-saraya-csrf"); if (origin !== expectedOrigin) throw new ApiError(403, "ORIGIN_DENIED", "مصدر الطلب غير مسموح", "Request origin denied"); if (!values["__Host-saraya_refresh"]) throw new ApiError(401, "REFRESH_COOKIE_REQUIRED", "ملف الجلسة مطلوب", "Refresh cookie required"); if (!headerCsrf || !values.saraya_csrf || !same(headerCsrf, values.saraya_csrf)) throw new ApiError(403, "CSRF_DENIED", "رمز الحماية غير صالح", "CSRF validation failed"); return { token: values["__Host-saraya_refresh"], web: true as const }; }
export const newCsrfToken = () => randomBytes(24).toString("base64url");
export function requestIp(request: Request) { const vercel = request.headers.get("x-vercel-forwarded-for")?.split(",")[0]?.trim(); if (vercel) return vercel; const trustedProxy = process.env.SARAYA_TRUST_PROXY_HEADERS === "1" ? request.headers.get("x-real-ip")?.trim() : null; if (trustedProxy) return trustedProxy; if (process.env.NODE_ENV !== "production") return "development"; throw new ApiError(503, "CLIENT_IP_UNAVAILABLE", "تعذر التحقق من مصدر الطلب", "Client IP is unavailable"); }
export function webSessionResponse(value: { accessToken: string; refreshToken: string }, status = 200) { const csrf = newCsrfToken(); const response = Response.json({ accessToken: value.accessToken, csrfToken: csrf }, { status }); response.headers.append("set-cookie", `__Host-saraya_refresh=${encodeURIComponent(value.refreshToken)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=2592000`); response.headers.append("set-cookie", `saraya_csrf=${encodeURIComponent(csrf)}; Path=/; Secure; SameSite=Strict; Max-Age=2592000`); return response; }
export function clearWebSessionCookies(response = new Response(null, { status: 204 })) { response.headers.append("set-cookie", "__Host-saraya_refresh=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0"); response.headers.append("set-cookie", "saraya_csrf=; Path=/; Secure; SameSite=Strict; Max-Age=0"); return response; }
