import { createHash, createHmac, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import { ApiError, type SarayaMembership, type SarayaPrincipal } from "./contracts";
export interface SessionRecord { id: string; familyId: string; generation: number; userId: string; refreshTokenHash: string; previousRefreshTokenHash: string | null; expiresAt: Date; revokedAt: Date | null; rotatedAt?: Date | null }
export interface SessionRepository { insert(record: SessionRecord): Promise<void>; findByRefreshHash(hash: string): Promise<SessionRecord | null>; findByPreviousRefreshHash(hash: string): Promise<SessionRecord | null>; rotate(id: string, expectedHash: string, nextHash: string, at: Date, generation: number): Promise<boolean>; revoke(id: string, at: Date): Promise<void>; revokeFamily(familyId: string, at: Date): Promise<void>; findActiveById?(id: string): Promise<SessionRecord | null> }
export interface LoadedUser { id: string; isActive: boolean; memberships: Array<SarayaMembership & { isActive?: boolean }> }
const tokenHash = (value: string) => createHash("sha256").update(value).digest("hex");
const encode = (value: unknown) => Buffer.from(JSON.stringify(value)).toString("base64url");
export function createSessionService(deps: { sessions: SessionRepository; loadUser(id: string): Promise<LoadedUser | null>; accessTokenSecret: string; now?: () => Date; generateToken?: () => string; hashToken?: (value: string) => string; accessTtlMs?: number; refreshTtlMs?: number }) {
  if (deps.accessTokenSecret.length < 32) throw new Error("Saraya access secret must be at least 32 characters");
  const now = deps.now ?? (() => new Date()); const generate = deps.generateToken ?? (() => randomBytes(32).toString("base64url")); const hash = deps.hashToken ?? tokenHash;
  const sign = (body: string) => createHmac("sha256", deps.accessTokenSecret).update(`saraya-access:v1:${body}`).digest("base64url");
  async function buildPrincipal(userId: string, sessionId: string): Promise<SarayaPrincipal> { const user = await deps.loadUser(userId); if (!user?.isActive) throw new ApiError(403, "USER_DISABLED", "الحساب معطل", "User account is disabled"); const memberships = user.memberships.filter((m) => m.isActive !== false); return { userId, sessionId, memberships, propertyIds: [...new Set(memberships.map((m) => m.propertyId))] }; }
  async function access(userId: string, sessionId: string) { const principal = await buildPrincipal(userId, sessionId); const body = encode({ ...principal, exp: now().getTime() + (deps.accessTtlMs ?? 900_000) }); return `${body}.${sign(body)}`; }
  return {
    async create(userId: string, id: string = randomUUID()) { const raw = generate(); await deps.sessions.insert({ id, familyId: randomUUID(), generation: 0, userId, refreshTokenHash: hash(raw), previousRefreshTokenHash: null, expiresAt: new Date(now().getTime() + (deps.refreshTtlMs ?? 2_592_000_000)), revokedAt: null }); return { accessToken: await access(userId, id), refreshToken: raw }; },
    async refresh(raw: string) { const oldHash = hash(raw); const replay = await deps.sessions.findByPreviousRefreshHash(oldHash); if (replay) { await deps.sessions.revokeFamily(replay.familyId, now()); throw new ApiError(401, "REFRESH_REUSE_DETECTED", "تم إنهاء الجلسة لحمايتها", "Refresh token reuse detected"); } const session = await deps.sessions.findByRefreshHash(oldHash); if (!session || session.revokedAt || session.expiresAt <= now()) throw new ApiError(401, "INVALID_REFRESH_TOKEN", "جلسة غير صالحة", "Invalid refresh token"); await buildPrincipal(session.userId, session.id); const next = generate(); if (!await deps.sessions.rotate(session.id, oldHash, hash(next), now(), session.generation)) { await deps.sessions.revokeFamily(session.familyId, now()); throw new ApiError(401, "REFRESH_REUSE_DETECTED", "تم إنهاء الجلسة لحمايتها", "Refresh token reuse detected"); } return { accessToken: await access(session.userId, session.id), refreshToken: next }; },
    revoke: (id: string) => deps.sessions.revoke(id, now()),
    async verifyAccess(raw: string): Promise<SarayaPrincipal> { const [body, signature, extra] = raw.split("."); if (!body || !signature || extra) throw new ApiError(401, "INVALID_ACCESS_TOKEN", "رمز الدخول غير صالح", "Invalid access token"); const a = Buffer.from(signature); const b = Buffer.from(sign(body)); if (a.length !== b.length || !timingSafeEqual(a, b)) throw new ApiError(401, "INVALID_ACCESS_TOKEN", "رمز الدخول غير صالح", "Invalid access token"); let parsed: SarayaPrincipal & { exp: number }; try { parsed = JSON.parse(Buffer.from(body, "base64url").toString("utf8")); } catch { throw new ApiError(401, "INVALID_ACCESS_TOKEN", "رمز الدخول غير صالح", "Invalid access token"); } if (parsed.exp <= now().getTime()) throw new ApiError(401, "ACCESS_TOKEN_EXPIRED", "انتهت جلسة الدخول", "Access token expired"); if (deps.sessions.findActiveById) { const active = await deps.sessions.findActiveById(parsed.sessionId); if (!active || active.revokedAt || active.expiresAt <= now()) throw new ApiError(401, "SESSION_REVOKED", "تم إنهاء الجلسة", "Session revoked"); } return buildPrincipal(parsed.userId, parsed.sessionId); },
  };
}
