import { ServerClient } from "postmark";
import { authorize, authorizeRoleGrant } from "@/lib/saraya/access/authorize";
import { ApiError } from "@/lib/saraya/auth/contracts";
import { handle, jsonBody, text } from "@/lib/saraya/auth/http";
import { createInvitationService } from "@/lib/saraya/auth/invitations";
import { requireSarayaPrincipal } from "@/lib/saraya/auth/request";
import { sessions } from "@/lib/saraya/auth/runtime";
import { invitationRepository } from "@/lib/saraya/auth/store";
import type { SarayaRole } from "@/lib/db/saraya-schema";
const roles: SarayaRole[] = ["super_admin", "property_manager", "accountant", "maintenance", "owner", "tenant"];
export async function POST(request: Request) { return handle(async () => { const principal = await requireSarayaPrincipal(request, sessions()); const body = await jsonBody(request); const propertyId = text(body, "propertyId"); authorize(principal, { propertyId, permission: "memberships:write" }); const role = text(body, "role") as SarayaRole; if (!roles.includes(role)) throw new ApiError(422, "INVALID_ROLE", "الدور غير صالح", "Invalid role"); const actorRole = principal.memberships.find((item) => item.propertyId === propertyId)!.role; authorizeRoleGrant(actorRole, role); const email = typeof body.email === "string" ? body.email : undefined; const phone = typeof body.phone === "string" ? body.phone : undefined; if (!email && !phone) throw new ApiError(422, "IDENTITY_REQUIRED", "البريد أو الهاتف مطلوب", "Email or phone is required"); const baseUrl = process.env.SARAYA_APP_URL; if (!baseUrl) throw new ApiError(503, "INVITATION_DELIVERY_NOT_CONFIGURED", "خدمة الدعوات غير مهيأة", "Invitation delivery is not configured"); const service = createInvitationService({ invitations: invitationRepository, mailer: { async sendInvitation(message) { const link = `${baseUrl}/activate?token=${encodeURIComponent(message.token)}`; if (message.email) { const key = process.env.POSTMARK_SERVER_TOKEN; const from = process.env.SARAYA_INVITATION_FROM; if (!key || !from) throw new ApiError(503, "EMAIL_NOT_CONFIGURED", "خدمة البريد غير مهيأة", "Email is not configured"); await new ServerClient(key).sendEmail({ From: from, To: message.email, Subject: "Saraya Square invitation", TextBody: link }); return; } const endpoint = process.env.SARAYA_SMS_WEBHOOK_URL; const key = process.env.SARAYA_SMS_WEBHOOK_SECRET; if (!endpoint || !key || !message.phone) throw new ApiError(503, "SMS_NOT_CONFIGURED", "خدمة الرسائل غير مهيأة", "SMS is not configured"); const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${key}` }, body: JSON.stringify({ to: message.phone, message: link }) }); if (!response.ok) throw new ApiError(502, "SMS_DELIVERY_FAILED", "تعذر إرسال الرسالة", "SMS delivery failed"); } } }); const invitation = await service.create({ propertyId, role, email, phone, invitedByUserId: principal.userId }); return Response.json({ id: invitation.id, expiresAt: invitation.expiresAt }, { status: 201 }); }); }
