"use client";

import Image from "next/image";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { useLocale } from "next-intl";
import { Camera, Check, Eye, EyeOff, KeyRound, Loader2, LockKeyhole, Mail, Phone, Save, ShieldCheck, Trash2, UserCog } from "lucide-react";
import { ADMIN_PERMISSION_KEYS, type AdminPermission, type AdminPermissions } from "@/lib/auth/admin-permissions";

type Admin = { id: string; fullName: string; email: string; phone: string | null; avatarUrl: string | null; role: "super_admin" | "admin" | "reviewer"; isActive: boolean; permissions: AdminPermissions };
const inputClass = "h-12 w-full rounded-xl border border-gray-200 bg-white px-4 text-sm font-bold text-[#082B67] outline-none transition placeholder:text-gray-400 focus:border-[#B4232A] focus:ring-4 focus:ring-red-50";
const permissionLabels: Record<AdminPermission, { ar: string; en: string }> = {
  manage_moderation: { ar: "إدارة بلاغات المحادثة", en: "Manage chat reports" },
  manage_training: { ar: "إدارة طلبات التدريب", en: "Training applications" },
  manage_careers: { ar: "إدارة الوظائف والمتقدمين", en: "Manage careers and applicants" },
  view_dashboard: { ar: "عرض لوحة التحكم", en: "View dashboard" }, manage_admins: { ar: "إدارة الأدمن", en: "Manage admins" }, manage_discounts: { ar: "أكواد الخصم", en: "Discount codes" }, manage_approvals: { ar: "الموافقات", en: "Approvals" }, manage_requests: { ar: "الطلبات", en: "Requests" }, manage_finance: { ar: "المالية", en: "Finance" }, manage_reviews: { ar: "التقييمات", en: "Reviews" }, manage_lawyers: { ar: "المحامين", en: "Lawyers" }, manage_notifications: { ar: "إشعارات التطبيق", en: "App notifications" }, manage_faq: { ar: "الأسئلة الشائعة", en: "FAQ" }, manage_about: { ar: "إدارة صفحة من نحن", en: "Manage About page" },
  manage_consultation_types: { ar: "إدارة أنواع الاستشارة والأسعار", en: "Manage consultation types and prices" },
  manage_terms_commissions: { ar: "إدارة الشروط والنسب", en: "Manage terms & commissions" },
};

export default function AdminProfileContent() {
  const locale = useLocale(); const isAr = locale === "ar"; const fileRef = useRef<HTMLInputElement>(null);
  const [admin, setAdmin] = useState<Admin | null>(null); const [fullName, setFullName] = useState(""); const [email, setEmail] = useState(""); const [phone, setPhone] = useState("");
  const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState("");
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [avatarBusy, setAvatarBusy] = useState(false); const [showPasswords, setShowPasswords] = useState(false);
  const [message, setMessage] = useState<{ ok: boolean; text: string } | null>(null);

  useEffect(() => { let active = true; fetch("/api/admin/me", { cache: "no-store" }).then(async (response) => ({ response, data: await response.json().catch(() => ({})) })).then(({ response, data }) => { if (!active) return; if (!response.ok) { window.location.href = `/${locale}/login/admin`; return; } const value = data.admin as Admin; setAdmin(value); setFullName(value.fullName ?? ""); setEmail(value.email ?? ""); setPhone(value.phone ?? ""); setLoading(false); }); return () => { active = false; }; }, [locale]);

  const errorText = (code: string) => ({ duplicate_email: isAr ? "البريد الإلكتروني مستخدم مسبقًا." : "Email is already in use.", incorrect_current_password: isAr ? "كلمة المرور الحالية غير صحيحة." : "Current password is incorrect.", current_password_required: isAr ? "أدخل كلمة المرور الحالية لتغيير البريد أو كلمة المرور." : "Enter your current password to change email or password.", password_mismatch: isAr ? "كلمتا المرور الجديدتان غير متطابقتين." : "New passwords do not match.", weak_password: isAr ? "كلمة المرور الجديدة يجب أن تكون 10 أحرف وتحتوي أحرفًا وأرقامًا." : "New password must be 10+ characters with letters and numbers.", invalid_phone: isAr ? "رقم الهاتف غير صحيح." : "Invalid phone number.", avatar_too_large: isAr ? "حجم الصورة يجب ألا يتجاوز 5MB." : "Avatar must be 5MB or smaller.", invalid_avatar_type: isAr ? "اختر صورة JPEG أو PNG أو WebP." : "Choose a JPEG, PNG, or WebP image.", avatar_storage_unavailable: isAr ? "خدمة رفع الصور غير مهيأة." : "Avatar storage is not configured." }[code] ?? (isAr ? "تعذر حفظ التعديلات." : "Could not save changes."));

  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setMessage(null); const response = await fetch("/api/admin/profile", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ fullName, email, phone, currentPassword, newPassword, confirmPassword }) }); const data = await response.json().catch(() => ({})); if (response.ok) { setAdmin((value) => value ? { ...value, ...data.admin } : data.admin); setCurrentPassword(""); setNewPassword(""); setConfirmPassword(""); setMessage({ ok: true, text: isAr ? "تم حفظ بيانات البروفايل بنجاح." : "Profile saved successfully." }); } else setMessage({ ok: false, text: errorText(data.error) }); setSaving(false); };
  const uploadAvatar = async (file?: File) => { if (!file) return; setAvatarBusy(true); setMessage(null); const form = new FormData(); form.set("avatar", file); const response = await fetch("/api/admin/profile/avatar", { method: "POST", body: form }); const data = await response.json().catch(() => ({})); if (response.ok) { setAdmin((value) => value ? { ...value, avatarUrl: data.avatarUrl } : value); setMessage({ ok: true, text: isAr ? "تم تحديث صورة البروفايل." : "Profile photo updated." }); } else setMessage({ ok: false, text: errorText(data.error) }); setAvatarBusy(false); if (fileRef.current) fileRef.current.value = ""; };
  const removeAvatar = async () => { setAvatarBusy(true); const response = await fetch("/api/admin/profile/avatar", { method: "DELETE" }); if (response.ok) { setAdmin((value) => value ? { ...value, avatarUrl: null } : value); setMessage({ ok: true, text: isAr ? "تم حذف صورة البروفايل." : "Profile photo removed." }); } else setMessage({ ok: false, text: errorText("") }); setAvatarBusy(false); };
  const permissions = admin?.role === "super_admin" ? ADMIN_PERMISSION_KEYS : ADMIN_PERMISSION_KEYS.filter((key) => admin?.permissions?.[key]);

  if (loading) return <main className="flex min-h-screen items-center justify-center bg-[#F7F8FA]"><Loader2 className="h-8 w-8 animate-spin text-[#B4232A]" /></main>;
  return <main className="min-h-screen bg-[#F7F8FA] px-5 py-10" dir={isAr ? "rtl" : "ltr"}><div className="mx-auto max-w-6xl">
    <section className="mb-6 rounded-3xl bg-[linear-gradient(135deg,#B4232A_0%,#8E1820_100%)] p-7 text-white shadow-[0_22px_60px_rgba(180,35,42,0.24)]"><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-white/12"><UserCog /></div><h1 className="text-2xl font-black sm:text-3xl">{isAr ? "البروفايل والأمان" : "Profile & Security"}</h1><p className="mt-2 text-sm leading-7 text-white/70">{isAr ? "حدّث بياناتك وصورة حسابك وإعدادات الأمان من مكان واحد." : "Update your details, account photo, and security settings in one place."}</p></section>
    {message ? <div className={`mb-5 flex items-center gap-2 rounded-2xl border px-4 py-3 text-sm font-bold ${message.ok ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-red-200 bg-red-50 text-red-700"}`}>{message.ok ? <Check className="h-4 w-4" /> : null}{message.text}</div> : null}
    <form onSubmit={submit} className="grid gap-6 lg:grid-cols-[330px_1fr]">
      <aside className="space-y-6"><section className="rounded-3xl border border-transparent bg-white transition hover:border-[#B4232A] focus-within:border-[#B4232A] p-6 text-center shadow-[0_16px_45px_rgba(7,17,31,0.06)]"><div className="relative mx-auto h-28 w-28 overflow-hidden rounded-full bg-[#082B67] text-white shadow-[0_12px_30px_rgba(8,43,103,0.22)]">{admin?.avatarUrl ? <Image src={admin.avatarUrl} alt="" fill sizes="112px" unoptimized className="object-cover" /> : <span className="flex h-full items-center justify-center text-4xl font-black">{admin?.fullName?.charAt(0).toUpperCase()}</span>}</div><h2 className="mt-4 text-lg font-black text-[#082B67]">{admin?.fullName}</h2><p className="mt-1 text-sm text-gray-500">{admin?.email}</p><div className="mt-4 flex justify-center gap-2"><button type="button" disabled={avatarBusy} onClick={() => fileRef.current?.click()} className="inline-flex items-center gap-2 rounded-xl bg-[#B4232A] px-3 py-2 text-xs font-extrabold text-white disabled:opacity-50">{avatarBusy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Camera className="h-4 w-4" />}{isAr ? "تغيير الصورة" : "Change photo"}</button>{admin?.avatarUrl ? <button type="button" disabled={avatarBusy} onClick={() => void removeAvatar()} className="rounded-xl border border-red-100 bg-red-50 p-2 text-red-700"><Trash2 className="h-4 w-4" /></button> : null}</div><input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => void uploadAvatar(event.target.files?.[0])} /><p className="mt-3 text-[11px] leading-5 text-gray-400">JPEG, PNG, WebP · 5MB</p></section>
        <section className="rounded-3xl border border-transparent bg-white transition hover:border-[#B4232A] focus-within:border-[#B4232A] p-5 shadow-[0_16px_45px_rgba(7,17,31,0.06)]"><div className="flex items-center gap-2 text-[#082B67]"><ShieldCheck className="h-5 w-5" /><h3 className="font-black">{isAr ? "الحساب والصلاحيات" : "Account & Permissions"}</h3></div><div className="mt-4 flex gap-2"><span className="rounded-full bg-[#082B67] px-3 py-1.5 text-xs font-black text-white">{admin?.role}</span><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-black text-emerald-700">{isAr ? "نشط" : "Active"}</span></div><div className="mt-4 flex flex-wrap gap-2">{permissions.map((key) => <span key={key} className="rounded-lg bg-red-50 px-2.5 py-1.5 text-[11px] font-bold text-[#B4232A]">{isAr ? permissionLabels[key].ar : permissionLabels[key].en}</span>)}</div><p className="mt-4 text-[11px] leading-5 text-gray-400">{isAr ? "نوع الحساب والصلاحيات تُدار من صفحة إدارة الأدمن." : "Role and permissions are managed from Admin Management."}</p></section></aside>
      <div className="space-y-6"><section className="rounded-3xl border border-transparent bg-white transition hover:border-[#B4232A] focus-within:border-[#B4232A] p-6 shadow-[0_16px_45px_rgba(7,17,31,0.06)]"><h2 className="text-lg font-black text-[#082B67]">{isAr ? "البيانات الشخصية" : "Personal Details"}</h2><p className="mt-1 text-xs text-gray-500">{isAr ? "يمكنك تعديل بيانات التواصل الخاصة بحسابك." : "Update your account contact details."}</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="text-sm font-extrabold text-[#082B67]">{isAr ? "الاسم الكامل" : "Full name"}<input required className={`${inputClass} mt-2`} value={fullName} onChange={(e) => setFullName(e.target.value)} /></label><label className="text-sm font-extrabold text-[#082B67]">{isAr ? "البريد الإلكتروني" : "Email"}<div className="relative mt-2"><Mail className="absolute start-4 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input required type="email" className={`${inputClass} ps-11`} value={email} onChange={(e) => setEmail(e.target.value)} /></div></label><label className="text-sm font-extrabold text-[#082B67] sm:col-span-2">{isAr ? "رقم الهاتف" : "Phone number"}<div className="relative mt-2"><Phone className="absolute start-4 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input type="tel" className={`${inputClass} ps-11`} value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="+973 0000 0000" /></div></label></div></section>
        <section className="rounded-3xl border border-transparent bg-white transition hover:border-[#B4232A] focus-within:border-[#B4232A] p-6 shadow-[0_16px_45px_rgba(7,17,31,0.06)]"><div className="flex items-center gap-2 text-[#082B67]"><LockKeyhole className="h-5 w-5" /><h2 className="text-lg font-black">{isAr ? "الأمان وكلمة المرور" : "Security & Password"}</h2></div><p className="mt-1 text-xs text-gray-500">{isAr ? "كلمة المرور الحالية مطلوبة فقط عند تغيير البريد أو كلمة المرور." : "Current password is required only when changing email or password."}</p><div className="mt-5 grid gap-5"><label className="text-sm font-extrabold text-[#082B67]">{isAr ? "كلمة المرور الحالية" : "Current password"}<div className="relative mt-2"><KeyRound className="absolute start-4 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input type={showPasswords ? "text" : "password"} className={`${inputClass} ps-11`} value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} /></div></label><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-extrabold text-[#082B67]">{isAr ? "كلمة المرور الجديدة" : "New password"}<input type={showPasswords ? "text" : "password"} className={`${inputClass} mt-2`} value={newPassword} onChange={(e) => setNewPassword(e.target.value)} /></label><label className="text-sm font-extrabold text-[#082B67]">{isAr ? "تأكيد كلمة المرور" : "Confirm password"}<input type={showPasswords ? "text" : "password"} className={`${inputClass} mt-2`} value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} /></label></div><button type="button" onClick={() => setShowPasswords((value) => !value)} className="inline-flex w-fit items-center gap-2 text-xs font-bold text-gray-500 hover:text-[#B4232A]">{showPasswords ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}{showPasswords ? (isAr ? "إخفاء كلمات المرور" : "Hide passwords") : (isAr ? "إظهار كلمات المرور" : "Show passwords")}</button></div></section>
        <button disabled={saving} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-[#B4232A] px-7 text-sm font-extrabold text-white shadow-[0_12px_28px_rgba(180,35,42,0.24)] transition hover:bg-[#991F25] disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}{saving ? (isAr ? "جاري الحفظ..." : "Saving...") : (isAr ? "حفظ التعديلات" : "Save Changes")}</button>
      </div>
    </form>
  </div></main>;
}
