"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { Archive, ArrowDown, ArrowUp, ImagePlus, Loader2, Pencil, RotateCcw, Save, Trash2, Users, X } from "lucide-react";

type Section = { id:string; romanLabel:string; headingAr:string; headingEn:string; position:number; archivedAt:string|null; updatedAt:string };
type Member = { id:string; sectionId:string; nameAr:string; nameEn:string; titleAr:string; titleEn:string; slug:string|null; schemaType:"Person"|"Organization"; featured:boolean; photoUrl:string|null; previousExperienceAr:string[]; previousExperienceEn:string[]; experienceAr:string[]; experienceEn:string[]; yearsOfExperienceAr:string; yearsOfExperienceEn:string; previousEmployerAr:string; previousEmployerEn:string; tasksAr:string[]; tasksEn:string[]; tasksLabelAr:string; tasksLabelEn:string; position:number; archivedAt:string|null; updatedAt:string };
type MemberFormState = Omit<Member,"id"|"photoUrl"|"position"|"archivedAt"|"updatedAt"|"slug"> & { slug:string };
type Data = { sections:Section[]; members:Member[] };
type Tab = "sections"|"members"|"archived";
const field="w-full rounded-xl border border-gray-200 bg-white px-4 py-3 text-sm font-bold text-[#082B67] outline-none transition focus:border-[#B4232A] focus:ring-4 focus:ring-red-50";
const card="rounded-3xl border border-transparent bg-white p-5 shadow-[0_14px_40px_rgba(7,17,31,0.055)] transition hover:border-[#B4232A] focus-within:border-[#B4232A]";
const emptyMember=(sectionId=""):MemberFormState=>({sectionId,nameAr:"",nameEn:"",titleAr:"",titleEn:"",slug:"",schemaType:"Person",featured:false,previousExperienceAr:[],previousExperienceEn:[],experienceAr:[],experienceEn:[],yearsOfExperienceAr:"",yearsOfExperienceEn:"",previousEmployerAr:"",previousEmployerEn:"",tasksAr:[],tasksEn:[],tasksLabelAr:"",tasksLabelEn:""});
const lines=(value:string)=>value.split("\n").map(x=>x.trim()).filter(Boolean);

export default function AboutAdminContent({isAr}:{isAr:boolean}){
 const [data,setData]=useState<Data>({sections:[],members:[]}); const [tab,setTab]=useState<Tab>("sections"); const [busy,setBusy]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 const [sectionEdit,setSectionEdit]=useState<Section|null>(null); const [sectionForm,setSectionForm]=useState({romanLabel:"",headingAr:"",headingEn:""});
 const [memberEdit,setMemberEdit]=useState<Member|null>(null); const [memberForm,setMemberForm]=useState(emptyMember()); const [search,setSearch]=useState(""); const [filter,setFilter]=useState("");
 const load=useCallback(async()=>{setBusy(true);const r=await fetch("/api/admin/about",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.ok)setData({sections:d.sections??[],members:d.members??[]});else setMessage(isAr?"تعذر تحميل البيانات":"Could not load data");setBusy(false)},[isAr]);
 useEffect(()=>{let active=true;fetch("/api/admin/about",{cache:"no-store"}).then(async r=>({r,d:await r.json().catch(()=>({}))})).then(({r,d})=>{if(!active)return;if(r.ok)setData({sections:d.sections??[],members:d.members??[]});else setMessage(isAr?"تعذر تحميل البيانات":"Could not load data");setBusy(false)});return()=>{active=false}},[isAr]);
 const activeSections=data.sections.filter(x=>!x.archivedAt);
 const shownMembers=useMemo(()=>data.members.filter(m=>(tab==="archived"?m.archivedAt:!m.archivedAt)&&(!filter||m.sectionId===filter)&&(!search||`${m.nameAr} ${m.nameEn} ${m.titleAr} ${m.titleEn}`.toLowerCase().includes(search.toLowerCase()))),[data.members,filter,search,tab]);
 async function request(url:string,method:string,body?:unknown){setSaving(true);setMessage("");const r=await fetch(url,{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));setSaving(false);if(!r.ok){setMessage(isAr?"تعذر تنفيذ العملية":"Action failed");return null}await load();setMessage(isAr?"تم حفظ التغييرات":"Changes saved");return d}
 async function saveSection(e:FormEvent){e.preventDefault();await request(sectionEdit?`/api/admin/about/sections/${sectionEdit.id}`:"/api/admin/about/sections",sectionEdit?"PATCH":"POST",sectionForm);setSectionEdit(null);setSectionForm({romanLabel:"",headingAr:"",headingEn:""})}
 async function saveMember(e:FormEvent){e.preventDefault();const d=await request(memberEdit?`/api/admin/about/members/${memberEdit.id}`:"/api/admin/about/members",memberEdit?"PATCH":"POST",memberForm);if(d){setMemberEdit(null);setMemberForm(emptyMember(activeSections[0]?.id))}}
 function editMember(m:Member){setMemberEdit(m);setMemberForm({...m,slug:m.slug??""});window.scrollTo({top:0,behavior:"smooth"})}
 async function action(kind:"sections"|"members",id:string,verb:"archive"|"restore"){await request(`/api/admin/about/${kind}/${id}`,"PATCH",{action:verb})}
 async function removeSection(s:Section){const count=data.members.filter(m=>m.sectionId===s.id).length;if(!confirm(isAr?`تنبيه: سيتم حذف القسم و ${count} عضو داخله نهائيًا. هل أنت متأكد؟`:`Warning: this permanently deletes the section and ${count} members. Continue?`))return;if(!confirm(isAr?"تأكيد أخير: لا يمكن التراجع عن الحذف النهائي.":"Final confirmation: permanent deletion cannot be undone."))return;await request(`/api/admin/about/sections/${s.id}`,"DELETE",{confirmation:"DELETE"})}
  async function removeMember(m:Member){if(confirm(isAr?"هل تريد حذف العضو نهائيًا؟":"Permanently delete this member?"))await request(`/api/admin/about/members/${m.id}`,"DELETE")}
 async function move(kind:"sections"|"members",items:Array<{id:string}>,index:number,delta:number,sectionId?:string){const next=[...items];const target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];await request(`/api/admin/about/${kind}/reorder`,"POST",{ids:next.map(x=>x.id),...(sectionId?{sectionId}:{})})}
 async function upload(member:Member,file?:File){if(!file)return;setSaving(true);const body=new FormData();body.set("photo",file);const r=await fetch(`/api/admin/about/members/${member.id}/photo`,{method:"POST",body});setSaving(false);if(r.ok)await load();else setMessage(isAr?"تعذر رفع الصورة":"Photo upload failed")}
 async function removePhoto(member:Member){if(!confirm(isAr?"حذف صورة العضو؟":"Remove member photo?"))return;await request(`/api/admin/about/members/${member.id}/photo`,"DELETE")}
 return <main className="min-h-screen bg-[#F7F8FA] px-4 py-8 text-[#082B67]"><div className="mx-auto max-w-7xl">
  <header className="mb-6 rounded-3xl bg-[#B4232A] p-6 text-white"><h1 className="text-2xl font-black">{isAr?"إدارة صفحة من نحن":"About Page Management"}</h1><p className="mt-2 text-white/75">{isAr?"إضافة وتعديل وترتيب وأرشفة الأقسام والأعضاء.":"Create, edit, order, and archive sections and members."}</p></header>
  <div className="mb-6 flex flex-wrap gap-2">{(["sections","members","archived"] as Tab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-xl px-4 py-2 text-sm font-black ${tab===t?"bg-[#082B67] text-white":"bg-white text-[#082B67]"}`}>{t==="sections"?(isAr?"الأقسام":"Sections"):t==="members"?(isAr?"الأعضاء":"Members"):(isAr?"المؤرشف":"Archived")}</button>)}</div>
  {message&&<p className="mb-4 rounded-xl bg-white p-3 text-sm font-bold">{message}</p>}
  {busy?<div className="flex min-h-60 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-[#B4232A]"/></div>:
  <div className="grid gap-6 lg:grid-cols-[360px_1fr]">
   {tab==="sections"?<form onSubmit={saveSection} className={`${card} h-fit space-y-3`}><div className="flex justify-between"><h2 className="font-black">{sectionEdit?(isAr?"تعديل القسم":"Edit section"):(isAr?"إضافة قسم":"Add section")}</h2>{sectionEdit&&<button type="button" onClick={()=>{setSectionEdit(null);setSectionForm({romanLabel:"",headingAr:"",headingEn:""})}}><X/></button>}</div><input required className={field} placeholder={isAr?"الترقيم مثل I":"Label, e.g. I"} value={sectionForm.romanLabel} onChange={e=>setSectionForm({...sectionForm,romanLabel:e.target.value})}/><input required className={field} placeholder="اسم القسم بالعربي" value={sectionForm.headingAr} onChange={e=>setSectionForm({...sectionForm,headingAr:e.target.value})}/><input required className={field} placeholder="English section name" value={sectionForm.headingEn} onChange={e=>setSectionForm({...sectionForm,headingEn:e.target.value})}/><button disabled={saving} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#B4232A] p-3 font-black text-white"><Save className="h-4 w-4"/>{isAr?"حفظ":"Save"}</button></form>:
   <MemberForm isAr={isAr} form={memberForm} setForm={setMemberForm} sections={activeSections} editing={!!memberEdit} saving={saving} onSubmit={saveMember} onCancel={()=>{setMemberEdit(null);setMemberForm(emptyMember(activeSections[0]?.id))}}/>}
   <section className="space-y-4">
    {tab==="sections"?activeSections.map((s,i)=><article key={s.id} className={card}><div className="flex items-center justify-between gap-3"><div><b>{s.romanLabel}. {isAr?s.headingAr:s.headingEn}</b><p className="mt-1 text-xs text-gray-400">{data.members.filter(m=>m.sectionId===s.id).length} {isAr?"عضو":"members"}</p></div><div className="flex gap-1"><button onClick={()=>move("sections",activeSections,i,-1)}><ArrowUp/></button><button onClick={()=>move("sections",activeSections,i,1)}><ArrowDown/></button><button onClick={()=>{setSectionEdit(s);setSectionForm({romanLabel:s.romanLabel,headingAr:s.headingAr,headingEn:s.headingEn})}}><Pencil/></button><button onClick={()=>action("sections",s.id,"archive")}><Archive/></button><button onClick={()=>removeSection(s)} className="text-red-700"><Trash2/></button></div></div></article>):
     <><div className="flex gap-2"><input className={field} placeholder={isAr?"بحث":"Search"} value={search} onChange={e=>setSearch(e.target.value)}/><select className={field} value={filter} onChange={e=>setFilter(e.target.value)}><option value="">{isAr?"كل الأقسام":"All sections"}</option>{data.sections.map(s=><option key={s.id} value={s.id}>{isAr?s.headingAr:s.headingEn}</option>)}</select></div>{tab==="archived"&&data.sections.filter(s=>s.archivedAt).map(s=><article key={s.id} className={card}><div className="flex justify-between"><b>{s.romanLabel}. {isAr?s.headingAr:s.headingEn}</b><div className="flex gap-2"><button onClick={()=>action("sections",s.id,"restore")}><RotateCcw/></button><button title={isAr?"حذف نهائي":"Permanent delete"} onClick={()=>removeSection(s)} className="text-red-700"><Trash2/></button></div></div></article>)}{shownMembers.map((m)=>{const section=data.sections.find(s=>s.id===m.sectionId);const scoped=shownMembers.filter(x=>x.sectionId===m.sectionId);const scopedIndex=scoped.findIndex(x=>x.id===m.id);return <article key={m.id} className={card}><div className="flex gap-4"><div className="h-20 w-20 shrink-0 overflow-hidden rounded-2xl bg-gray-100">{m.photoUrl?<img src={m.photoUrl} alt="" className="h-full w-full object-cover"/>:<Users className="m-6 text-gray-400"/>}</div><div className="min-w-0 flex-1"><b>{isAr?(m.nameAr||m.titleAr):(m.nameEn||m.titleEn)}</b><p className="text-sm text-gray-500">{isAr?m.titleAr:m.titleEn}</p><p className="text-xs text-[#B4232A]">{section?(isAr?section.headingAr:section.headingEn):""}</p><div className="mt-3 flex flex-wrap gap-2">{!m.archivedAt&&<><button onClick={()=>move("members",scoped,scopedIndex,-1,m.sectionId)}><ArrowUp/></button><button onClick={()=>move("members",scoped,scopedIndex,1,m.sectionId)}><ArrowDown/></button></>}<button onClick={()=>editMember(m)}><Pencil/></button><label className="cursor-pointer"><ImagePlus/><input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void upload(m,e.target.files?.[0])}/></label>{m.photoUrl&&<button onClick={()=>removePhoto(m)} className="text-red-700"><X/></button>}{m.archivedAt?<button onClick={()=>action("members",m.id,"restore")}><RotateCcw/></button>:<button onClick={()=>action("members",m.id,"archive")}><Archive/></button>}<button title={isAr?"حذف نهائي":"Permanent delete"} onClick={()=>removeMember(m)} className="text-red-700"><Trash2/></button></div></div></div></article>})}</>}
    {((tab==="sections"&&!activeSections.length)||(tab!=="sections"&&!shownMembers.length))&&<div className={`${card} py-14 text-center text-gray-400`}>{isAr?"لا توجد بيانات":"No data"}</div>}
   </section>
  </div>}</div></main>
}

function MemberForm({isAr,form,setForm,sections,editing,saving,onSubmit,onCancel}:{isAr:boolean;form:ReturnType<typeof emptyMember>;setForm:(v:ReturnType<typeof emptyMember>)=>void;sections:Section[];editing:boolean;saving:boolean;onSubmit:(e:FormEvent)=>void;onCancel:()=>void}){
 const set=(k:keyof typeof form,v:unknown)=>setForm({...form,[k]:v});
 return <form onSubmit={onSubmit} className={`${card} h-fit space-y-3`}><div className="flex justify-between"><h2 className="font-black">{editing?(isAr?"تعديل العضو":"Edit member"):(isAr?"إضافة عضو":"Add member")}</h2>{editing&&<button type="button" onClick={onCancel}><X/></button>}</div>
 <select required className={field} value={form.sectionId} onChange={e=>set("sectionId",e.target.value)}><option value="">{isAr?"اختر القسم":"Choose section"}</option>{sections.map(s=><option key={s.id} value={s.id}>{isAr?s.headingAr:s.headingEn}</option>)}</select>
 <div className="grid grid-cols-2 gap-2"><input className={field} placeholder="الاسم بالعربي" value={form.nameAr} onChange={e=>set("nameAr",e.target.value)}/><input className={field} placeholder="English name" value={form.nameEn} onChange={e=>set("nameEn",e.target.value)}/></div>
 <div className="grid grid-cols-2 gap-2"><input required className={field} placeholder="المسمى بالعربي" value={form.titleAr} onChange={e=>set("titleAr",e.target.value)}/><input required className={field} placeholder="English title" value={form.titleEn} onChange={e=>set("titleEn",e.target.value)}/></div>
 <div className="grid grid-cols-2 gap-2"><input className={field} placeholder="slug" value={form.slug} onChange={e=>set("slug",e.target.value)}/><select className={field} value={form.schemaType} onChange={e=>set("schemaType",e.target.value)}><option value="Person">Person</option><option value="Organization">Organization</option></select></div>
 <label className="flex gap-2 text-sm font-bold"><input type="checkbox" checked={form.featured} onChange={e=>set("featured",e.target.checked)}/>{isAr?"عضو مميز":"Featured member"}</label>
 {([["previousExperienceAr","الخبرات بالعربي"],["previousExperienceEn","Experience in English"],["experienceAr","مجالات الخبرة بالعربي"],["experienceEn","Expertise in English"],["tasksAr","المهام بالعربي"],["tasksEn","Tasks in English"]] as const).map(([k,p])=><textarea key={k} className={field} rows={3} placeholder={p+" — سطر لكل عنصر"} value={form[k].join("\n")} onChange={e=>set(k,lines(e.target.value))}/>)}
 {([["yearsOfExperienceAr","سنوات الخبرة بالعربي"],["yearsOfExperienceEn","Years of experience"],["previousEmployerAr","جهة العمل السابقة بالعربي"],["previousEmployerEn","Previous employer"],["tasksLabelAr","عنوان المهام بالعربي"],["tasksLabelEn","Tasks label"]] as const).map(([k,p])=><input key={k} className={field} placeholder={p} value={form[k]} onChange={e=>set(k,e.target.value)}/>)}
 <button disabled={saving} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#B4232A] p-3 font-black text-white"><Save className="h-4 w-4"/>{isAr?"حفظ":"Save"}</button></form>
}
