import "server-only";
import { and, asc, eq, isNull, max } from "drizzle-orm";
import { db, schema } from "@/lib/db/client";
import { execSections, type ExecMember, type ExecSection } from "@/app/[locale]/about/team-data";
import { assertCompleteAboutOrder } from "./domain";
import { AboutManagementError, type AboutMemberInput, type AboutSectionInput } from "./types";

type Context = { adminId: string };
const bioValues = (member: ExecMember) => ({
  previousExperienceAr: member.bio?.previousExperience?.ar ?? [], previousExperienceEn: member.bio?.previousExperience?.en ?? [],
  experienceAr: member.bio?.experience?.ar ?? [], experienceEn: member.bio?.experience?.en ?? [],
  yearsOfExperienceAr: member.bio?.yearsOfExperience?.ar ?? "", yearsOfExperienceEn: member.bio?.yearsOfExperience?.en ?? "",
  previousEmployerAr: member.bio?.previousEmployer?.ar ?? "", previousEmployerEn: member.bio?.previousEmployer?.en ?? "",
  tasksAr: member.bio?.tasks.ar ?? [], tasksEn: member.bio?.tasks.en ?? [], tasksLabelAr: member.bio?.tasksLabel?.ar ?? "", tasksLabelEn: member.bio?.tasksLabel?.en ?? "",
});

async function ensureSeeded() {
  const existing = await db.select({ id: schema.aboutSections.id }).from(schema.aboutSections).limit(1);
  if (existing.length) return;
  await db.transaction(async (tx) => {
    await tx.insert(schema.aboutSections).values(execSections.map((section, position) => ({ seedKey: `legacy-section-${position}`, romanLabel: section.roman, headingAr: section.heading.ar, headingEn: section.heading.en, position }))).onConflictDoNothing();
    const sections = await tx.select().from(schema.aboutSections).orderBy(asc(schema.aboutSections.position));
    for (const [sectionPosition, section] of execSections.entries()) {
      const row = sections.find((item) => item.seedKey === `legacy-section-${sectionPosition}`); if (!row) continue;
      await tx.insert(schema.aboutMembers).values(section.members.map((member, position) => ({
        seedKey: `legacy-member-${sectionPosition}-${position}`, sectionId: row.id, nameAr: member.name?.ar ?? "", nameEn: member.name?.en ?? "",
        titleAr: member.title.ar, titleEn: member.title.en, slug: member.slug ?? null, schemaType: member.schemaType ?? "Person",
        featured: member.featured ?? false, photoUrl: member.photo ?? null, position, ...bioValues(member),
      }))).onConflictDoNothing();
    }
  });
}

export async function listAdminAbout() { await ensureSeeded(); const [sections, members] = await Promise.all([db.select().from(schema.aboutSections).orderBy(asc(schema.aboutSections.position)), db.select().from(schema.aboutMembers).orderBy(asc(schema.aboutMembers.sectionId), asc(schema.aboutMembers.position))]); return { sections, members }; }
export async function createSection(input: AboutSectionInput, c: Context) { const [{ position }] = await db.select({ position: max(schema.aboutSections.position) }).from(schema.aboutSections).where(isNull(schema.aboutSections.archivedAt)); const [row] = await db.insert(schema.aboutSections).values({ ...input, position: (position ?? -1) + 1, createdByAdminId: c.adminId, updatedByAdminId: c.adminId }).returning(); return row; }
export async function updateSection(id: string, input: AboutSectionInput, c: Context) { const [row] = await db.update(schema.aboutSections).set({ ...input, updatedAt: new Date(), updatedByAdminId: c.adminId }).where(eq(schema.aboutSections.id, id)).returning(); if (!row) throw new AboutManagementError("section_not_found", 404); return row; }
export async function sectionAction(id: string, action: "archive" | "restore", c: Context) { const archived = action === "archive"; const [row] = await db.update(schema.aboutSections).set({ archivedAt: archived ? new Date() : null, archivedByAdminId: archived ? c.adminId : null, updatedAt: new Date(), updatedByAdminId: c.adminId }).where(eq(schema.aboutSections.id, id)).returning(); if (!row) throw new AboutManagementError("section_not_found", 404); return row; }
export async function deleteSection(id: string) { return db.transaction(async (tx) => { const members = await tx.select({ key: schema.aboutMembers.photoStorageKey }).from(schema.aboutMembers).where(eq(schema.aboutMembers.sectionId, id)); const deleted = await tx.delete(schema.aboutSections).where(eq(schema.aboutSections.id, id)).returning({ id: schema.aboutSections.id }); if (!deleted.length) throw new AboutManagementError("section_not_found", 404); return { deletedMemberCount: members.length, managedPhotoStorageKeys: members.flatMap((m) => m.key ? [m.key] : []) }; }); }
export async function createMember(input: AboutMemberInput, c: Context) { const [{ position }] = await db.select({ position: max(schema.aboutMembers.position) }).from(schema.aboutMembers).where(and(eq(schema.aboutMembers.sectionId, input.sectionId), isNull(schema.aboutMembers.archivedAt))); const [row] = await db.insert(schema.aboutMembers).values({ ...input, slug: input.slug || null, position: (position ?? -1) + 1, createdByAdminId: c.adminId, updatedByAdminId: c.adminId }).returning(); return row; }
export async function updateMember(id: string, input: AboutMemberInput, c: Context) { const [row] = await db.update(schema.aboutMembers).set({ ...input, slug: input.slug || null, updatedAt: new Date(), updatedByAdminId: c.adminId }).where(eq(schema.aboutMembers.id, id)).returning(); if (!row) throw new AboutManagementError("member_not_found", 404); return row; }
export async function memberAction(id: string, action: "archive" | "restore", c: Context) { const archived = action === "archive"; const [row] = await db.update(schema.aboutMembers).set({ archivedAt: archived ? new Date() : null, archivedByAdminId: archived ? c.adminId : null, updatedAt: new Date(), updatedByAdminId: c.adminId }).where(eq(schema.aboutMembers.id, id)).returning(); if (!row) throw new AboutManagementError("member_not_found", 404); return row; }
export async function deleteMember(id: string) { const [row] = await db.delete(schema.aboutMembers).where(eq(schema.aboutMembers.id, id)).returning({ key: schema.aboutMembers.photoStorageKey }); if (!row) throw new AboutManagementError("member_not_found", 404); return { managedPhotoStorageKey: row.key }; }
export async function reorderSections(ids: string[], c: Context) { await db.transaction(async (tx) => { const current = await tx.select({ id: schema.aboutSections.id }).from(schema.aboutSections).where(isNull(schema.aboutSections.archivedAt)); assertCompleteAboutOrder(current.map(x => x.id), ids); await Promise.all(ids.map((id, position) => tx.update(schema.aboutSections).set({ position, updatedByAdminId: c.adminId, updatedAt: new Date() }).where(eq(schema.aboutSections.id, id)))); }); }
export async function reorderMembers(sectionId: string, ids: string[], c: Context) { await db.transaction(async (tx) => { const current = await tx.select({ id: schema.aboutMembers.id }).from(schema.aboutMembers).where(and(eq(schema.aboutMembers.sectionId, sectionId), isNull(schema.aboutMembers.archivedAt))); assertCompleteAboutOrder(current.map(x => x.id), ids); await Promise.all(ids.map((id, position) => tx.update(schema.aboutMembers).set({ position, updatedByAdminId: c.adminId, updatedAt: new Date() }).where(and(eq(schema.aboutMembers.id, id), eq(schema.aboutMembers.sectionId, sectionId))))); }); }
export async function setMemberPhoto(id: string, photoUrl: string | null, photoStorageKey: string | null, c: Context) { const [row] = await db.update(schema.aboutMembers).set({ photoUrl, photoStorageKey, updatedByAdminId: c.adminId, updatedAt: new Date() }).where(eq(schema.aboutMembers.id, id)).returning(); if (!row) throw new AboutManagementError("member_not_found", 404); return row; }

function mapMember(row: typeof schema.aboutMembers.$inferSelect): ExecMember { const hasBio = row.previousExperienceAr.length || row.previousExperienceEn.length || row.experienceAr.length || row.experienceEn.length || row.yearsOfExperienceAr || row.yearsOfExperienceEn || row.previousEmployerAr || row.previousEmployerEn || row.tasksAr.length || row.tasksEn.length; return { title: { ar: row.titleAr, en: row.titleEn }, ...(row.nameAr && row.nameEn ? { name: { ar: row.nameAr, en: row.nameEn } } : {}), featured: row.featured, ...(row.photoUrl ? { photo: row.photoUrl } : {}), ...(row.slug ? { slug: row.slug } : {}), schemaType: row.schemaType as "Person" | "Organization", ...(hasBio ? { bio: { ...(row.previousExperienceAr.length || row.previousExperienceEn.length ? { previousExperience: { ar: row.previousExperienceAr, en: row.previousExperienceEn } } : {}), ...(row.experienceAr.length || row.experienceEn.length ? { experience: { ar: row.experienceAr, en: row.experienceEn } } : {}), ...(row.yearsOfExperienceAr || row.yearsOfExperienceEn ? { yearsOfExperience: { ar: row.yearsOfExperienceAr, en: row.yearsOfExperienceEn } } : {}), ...(row.previousEmployerAr || row.previousEmployerEn ? { previousEmployer: { ar: row.previousEmployerAr, en: row.previousEmployerEn } } : {}), tasks: { ar: row.tasksAr, en: row.tasksEn }, ...(row.tasksLabelAr || row.tasksLabelEn ? { tasksLabel: { ar: row.tasksLabelAr, en: row.tasksLabelEn } } : {}) } } : {}) }; }
export async function getPublicAboutSections(): Promise<ExecSection[]> { await ensureSeeded(); const [sections, members] = await Promise.all([db.select().from(schema.aboutSections).where(isNull(schema.aboutSections.archivedAt)).orderBy(asc(schema.aboutSections.position)), db.select().from(schema.aboutMembers).where(isNull(schema.aboutMembers.archivedAt)).orderBy(asc(schema.aboutMembers.position))]); return sections.map(section => ({ roman: section.romanLabel, heading: { ar: section.headingAr, en: section.headingEn }, members: members.filter(member => member.sectionId === section.id).map(mapMember) })).filter(section => section.members.length > 0); }
